In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/duongquanganh/processed-data-v6/processed_val.csv
/kaggle/input/datasets/duongquanganh/processed-data-v6/processed_train.csv
/kaggle/input/datasets/duongquanganh/processed-data-v6/processed_test.csv

In [2]:
import csv

In [3]:
TRAIN_PATH = "/kaggle/input/datasets/duongquanganh/processed-data-v6/processed_train.csv"
VAL_PATH = "/kaggle/input/datasets/duongquanganh/processed-data-v6/processed_val.csv"
TEST_PATH = "/kaggle/input/datasets/duongquanganh/processed-data-v6/processed_test.csv"

In [4]:
def process(path):
    raw_reviews = []
    cleaned_reviews = []
    ws_reviews = []
    full_labels = []
    aspect_labels = []
    aspect_category_labels = []
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            raw_review = row.get("raw_reviews").strip()
            raw_reviews.append(raw_review)

            cleaned_review = row.get("cleaned_reviews").strip()
            cleaned_reviews.append(cleaned_review)

            ws_review = row.get("ws_reviews").strip()
            ws_reviews.append(ws_review)
            
            labels = row.get("full_labels").strip()
            full_labels.append(labels)

            review_aspects = row.get("aspect_labels").strip()
            review_aspect_categories = row.get("aspect_category_labels").strip()
            aspect_labels.append(review_aspects)
            aspect_category_labels.append(review_aspect_categories)

    return raw_reviews, cleaned_reviews, ws_reviews, full_labels, aspect_labels, aspect_category_labels

In [5]:
train_raw_reviews, train_cleaned_reviews, train_ws_reviews, train_labels, train_aspect_labels, train_aspect_category_labels = process(TRAIN_PATH)
val_raw_reviews, val_cleaned_reviews, val_ws_reviews, val_labels, val_aspect_labels, val_aspect_category_labels = process(VAL_PATH)
test_raw_reviews, test_cleaned_reviews, test_ws_reviews, test_labels, test_aspect_labels, test_aspect_category_labels = process(TEST_PATH)

len(train_raw_reviews), len(val_raw_reviews), len(test_raw_reviews)

(2961, 1290, 500)

In [6]:
!pip install -q transformers tqdm

In [7]:
import json
import math
import random
import re
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from tqdm.auto import tqdm
from transformers import AutoModel, AutoTokenizer, get_linear_schedule_with_warmup

SEED = 42
MODEL_NAME = "vinai/phobert-base"
MAX_LENGTH = 256
TRAIN_BATCH_SIZE = 16
EVAL_BATCH_SIZE = 32
LEARNING_RATE = 9e-5
WEIGHT_DECAY = 0.01
NUM_EPOCHS = 140
PATIENCE = 140
WARMUP_RATIO = 0.0
THRESHOLD_ENTITY = 0.5
THRESHOLD_ASPECT = 0.5
LOSS_WEIGHTS = {"entity": 2.0, "aspect": 3.0, "polarity": 1.0}

OUTPUT_DIR = Path("/kaggle/working/hierarchical_outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(SEED)

Device: cuda

In [8]:
REQUIRED_COLUMNS = ["raw_reviews", "cleaned_reviews", "ws_reviews", "full_labels", "aspect_labels", "aspect_category_labels"]

def validate_schema(path: str, required_columns: List[str]):
    df = pd.read_csv(path, encoding="utf-8-sig")
    missing = [c for c in required_columns if c not in df.columns]
    if missing:
        raise ValueError(f"{path} is missing required columns: {missing}")
    return df

train_df_raw = validate_schema(TRAIN_PATH, REQUIRED_COLUMNS)
val_df_raw = validate_schema(VAL_PATH, REQUIRED_COLUMNS)
test_df_raw = validate_schema(TEST_PATH, REQUIRED_COLUMNS)

print("Schema OK")
print("Train/Val/Test:", len(train_df_raw), len(val_df_raw), len(test_df_raw))

def split_pipe_labels(value: str) -> List[str]:
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return []
    text = str(value).strip()
    if not text:
        return []
    return [x.strip() for x in text.split("|") if x.strip()]

FULL_LABEL_PATTERN = re.compile(r"\{\s*([^,{}]+)\s*,\s*([^{}]+?)\s*\}")

def parse_full_label(full_label: str) -> List[Tuple[str, str]]:
    if full_label is None or (isinstance(full_label, float) and math.isnan(full_label)):
        return []
    text = str(full_label).strip()
    if not text:
        return []
    pairs = []
    for aspect_category, sentiment in FULL_LABEL_PATTERN.findall(text):
        pairs.append((aspect_category.strip(), sentiment.strip().lower()))
    return pairs

def normalize_sentiment(label: str) -> str:
    s = (label or "").strip().lower()
    if s in {"positive", "negative", "neutral"}:
        return s
    return "neutral"

def debug_raw_label_quality(df: pd.DataFrame, split_name: str):
    empty_aspect_category = 0
    empty_aspect = 0
    empty_full = 0
    parse_failed = 0
    mismatch_non_empty = 0

    for _, row in df.iterrows():
        aspect_category_text = row.get("aspect_category_labels", "")
        aspect_text = row.get("aspect_labels", "")
        full_text = row.get("full_labels", "")

        ac_list = split_pipe_labels(aspect_category_text)
        a_list = split_pipe_labels(aspect_text)
        full_pairs = parse_full_label(full_text)
        full_cats = [ac for ac, _ in full_pairs]

        if not ac_list:
            empty_aspect_category += 1
        if not a_list:
            empty_aspect += 1
        if str(full_text).strip() == "":
            empty_full += 1
        if str(full_text).strip() != "" and len(full_pairs) == 0:
            parse_failed += 1
        if ac_list and full_cats:
            # Aspect categories present in full_label but missing from aspect_category_label column.
            miss = [x for x in full_cats if x not in ac_list]
            if miss:
                mismatch_non_empty += 1

    n = len(df)
    print(f"[{split_name}] empty aspect_category_label: {empty_aspect_category}/{n}")
    print(f"[{split_name}] empty aspect_label: {empty_aspect}/{n}")
    print(f"[{split_name}] empty full_label: {empty_full}/{n}")
    print(f"[{split_name}] full_label parse_failed (non-empty but no pair): {parse_failed}/{n}")
    print(f"[{split_name}] rows with mismatch between aspect_category_label and full_label: {mismatch_non_empty}/{n}")

debug_raw_label_quality(train_df_raw, "train")
debug_raw_label_quality(val_df_raw, "val")
debug_raw_label_quality(test_df_raw, "test")

Schema OK
Train/Val/Test: 2961 1290 500
[train] empty aspect_category_label: 0/2961
[train] empty aspect_label: 0/2961
[train] empty full_label: 0/2961
[train] full_label parse_failed (non-empty but no pair): 0/2961
[train] rows with mismatch between aspect_category_label and full_label: 0/2961
[val] empty aspect_category_label: 0/1290
[val] empty aspect_label: 0/1290
[val] empty full_label: 0/1290
[val] full_label parse_failed (non-empty but no pair): 0/1290
[val] rows with mismatch between aspect_category_label and full_label: 0/1290
[test] empty aspect_category_label: 0/500
[test] empty aspect_label: 0/500
[test] empty full_label: 0/500
[test] full_label parse_failed (non-empty but no pair): 0/500
[test] rows with mismatch between aspect_category_label and full_label: 0/500

In [9]:
SENTIMENT_SPACE = ["negative", "neutral", "positive"]
sentiment2id = {s: i for i, s in enumerate(SENTIMENT_SPACE)}
id2sentiment = {i: s for s, i in sentiment2id.items()}

def build_records(df: pd.DataFrame) -> List[Dict]:
    records = []
    for _, row in df.iterrows():
        ws_review = str(row.get("ws_reviews", "") or "").strip()
        full_label = str(row.get("full_labels", "") or "").strip()
        aspect_text = row.get("aspect_labels", "")
        aspect_category_text = row.get("aspect_category_labels", "")

        full_pairs = parse_full_label(full_label)
        aspect_categories = split_pipe_labels(aspect_category_text)
        if not aspect_categories:
            aspect_categories = [ac for ac, _ in full_pairs]

        aspects = split_pipe_labels(aspect_text)
        if not aspects and aspect_categories:
            aspects = [ac.split("#", 1)[0] for ac in aspect_categories]

        polarity_by_aspect_category = OrderedDict()
        for ac, pol in full_pairs:
            polarity_by_aspect_category[ac] = normalize_sentiment(pol)

        records.append({
            "ws_review": ws_review,
            "full_label": full_label,
            "aspects": list(OrderedDict.fromkeys(aspects)),
            "aspect_categories": list(OrderedDict.fromkeys(aspect_categories)),
            "polarity_by_aspect_category": polarity_by_aspect_category,
        })
    return records

train_records = build_records(train_df_raw)
val_records = build_records(val_df_raw)
test_records = build_records(test_df_raw)

all_records = train_records + val_records + test_records
all_aspects = sorted({a for r in all_records for a in r["aspects"] if a})
all_aspect_categories = sorted({ac for r in all_records for ac in r["aspect_categories"] if ac})

aspect2id = {a: i for i, a in enumerate(all_aspects)}
id2aspect = {i: a for a, i in aspect2id.items()}
aspect_category2id = {ac: i for i, ac in enumerate(all_aspect_categories)}
id2aspect_category = {i: ac for ac, i in aspect_category2id.items()}

taxonomy = {
    "aspects": all_aspects,
    "aspect_categories": all_aspect_categories,
    "sentiments": SENTIMENT_SPACE,
    "aspect2id": aspect2id,
    "aspect_category2id": aspect_category2id,
    "sentiment2id": sentiment2id,
}

with open(OUTPUT_DIR / "taxonomy.json", "w", encoding="utf-8") as f:
    json.dump(taxonomy, f, ensure_ascii=False, indent=2)

print("Taxonomy frozen")
print("num_aspects:", len(all_aspects))
print("num_aspect_categories:", len(all_aspect_categories))

def debug_mapping_consistency(records: List[Dict], split_name: str):
    unknown_aspects = 0
    unknown_aspect_categories = 0
    for rec in records:
        for a in rec["aspects"]:
            if a not in aspect2id:
                unknown_aspects += 1
        for ac in rec["aspect_categories"]:
            if ac not in aspect_category2id:
                unknown_aspect_categories += 1
    print(f"[{split_name}] unknown aspects in mapping: {unknown_aspects}")
    print(f"[{split_name}] unknown aspect categories in mapping: {unknown_aspect_categories}")

def debug_label_distribution(records: List[Dict], split_name: str):
    n = len(records)
    cat_count = {ac: 0 for ac in all_aspect_categories}
    ent_count = {a: 0 for a in all_aspects}

    for rec in records:
        for ac in rec["aspect_categories"]:
            if ac in cat_count:
                cat_count[ac] += 1
        for a in rec["aspects"]:
            if a in ent_count:
                ent_count[a] += 1

    cat_rate = {k: (v / (n + 1e-9)) for k, v in cat_count.items()}
    ent_rate = {k: (v / (n + 1e-9)) for k, v in ent_count.items()}

    top_cat = sorted(cat_rate.items(), key=lambda x: x[1], reverse=True)[:10]
    top_ent = sorted(ent_rate.items(), key=lambda x: x[1], reverse=True)[:10]
    zero_cat = [k for k, v in cat_count.items() if v == 0]
    zero_ent = [k for k, v in ent_count.items() if v == 0]

    print(f"[{split_name}] top-10 aspect_category positive rates:")
    for k, v in top_cat:
        print(f"  {k}: rate={v:.4f}, support={cat_count[k]}")

    print(f"[{split_name}] top-10 entity positive rates:")
    for k, v in top_ent:
        print(f"  {k}: rate={v:.4f}, support={ent_count[k]}")

    print(f"[{split_name}] aspect_category with zero support: {len(zero_cat)}")
    print(f"[{split_name}] entity with zero support: {len(zero_ent)}")

debug_mapping_consistency(train_records, "train")
debug_mapping_consistency(val_records, "val")
debug_mapping_consistency(test_records, "test")

debug_label_distribution(train_records, "train")
debug_label_distribution(val_records, "val")
debug_label_distribution(test_records, "test")

Taxonomy frozen
num_aspects: 6
num_aspect_categories: 12
[train] unknown aspects in mapping: 0
[train] unknown aspect categories in mapping: 0
[val] unknown aspects in mapping: 0
[val] unknown aspect categories in mapping: 0
[test] unknown aspects in mapping: 0
[test] unknown aspect categories in mapping: 0
[train] top-10 aspect_category positive rates:
  FOOD#QUALITY: rate=0.8977, support=2658
  FOOD#STYLE&OPTIONS: rate=0.5897, support=1746
  FOOD#PRICES: rate=0.4732, support=1401
  RESTAURANT#GENERAL: rate=0.2888, support=855
  SERVICE#GENERAL: rate=0.2685, support=795
  AMBIENCE#GENERAL: rate=0.2489, support=737
  LOCATION#GENERAL: rate=0.1260, support=373
  RESTAURANT#PRICES: rate=0.0888, support=263
  RESTAURANT#MISCELLANEOUS: rate=0.0510, support=151
  DRINKS#QUALITY: rate=0.0385, support=114
[train] top-10 entity positive rates:
  FOOD: rate=0.9672, support=2864
  RESTAURANT: rate=0.3705, support=1097
  SERVICE: rate=0.2685, support=795
  AMBIENCE: rate=0.2489, support=737
  LOCATION: rate=0.1260, support=373
  DRINKS: rate=0.0807, support=239
[train] aspect_category with zero support: 0
[train] entity with zero support: 0
[val] top-10 aspect_category positive rates:
  FOOD#QUALITY: rate=0.8992, support=1160
  FOOD#PRICES: rate=0.5612, support=724
  FOOD#STYLE&OPTIONS: rate=0.4000, support=516
  RESTAURANT#GENERAL: rate=0.1791, support=231
  SERVICE#GENERAL: rate=0.1767, support=228
  AMBIENCE#GENERAL: rate=0.1589, support=205
  LOCATION#GENERAL: rate=0.1039, support=134
  RESTAURANT#MISCELLANEOUS: rate=0.0907, support=117
  DRINKS#PRICES: rate=0.0341, support=44
  DRINKS#QUALITY: rate=0.0302, support=39
[val] top-10 entity positive rates:
  FOOD: rate=0.9806, support=1265
  RESTAURANT: rate=0.2667, support=344
  SERVICE: rate=0.1767, support=228
  AMBIENCE: rate=0.1589, support=205
  LOCATION: rate=0.1039, support=134
  DRINKS: rate=0.0605, support=78
[val] aspect_category with zero support: 0
[val] entity with zero support: 0
[test] top-10 aspect_category positive rates:
  FOOD#QUALITY: rate=0.9140, support=457
  FOOD#STYLE&OPTIONS: rate=0.8060, support=403
  FOOD#PRICES: rate=0.6620, support=331
  AMBIENCE#GENERAL: rate=0.5100, support=255
  RESTAURANT#GENERAL: rate=0.4460, support=223
  LOCATION#GENERAL: rate=0.3580, support=179
  SERVICE#GENERAL: rate=0.3500, support=175
  RESTAURANT#MISCELLANEOUS: rate=0.2600, support=130
  DRINKS#PRICES: rate=0.1520, support=76
  RESTAURANT#PRICES: rate=0.1460, support=73
[test] top-10 entity positive rates:
  FOOD: rate=0.9560, support=478
  RESTAURANT: rate=0.6400, support=320
  AMBIENCE: rate=0.5100, support=255
  LOCATION: rate=0.3580, support=179
  SERVICE: rate=0.3500, support=175
  DRINKS: rate=0.2340, support=117
[test] aspect_category with zero support: 0
[test] entity with zero support: 0

In [10]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

class ABSAHierDataset(Dataset):
    def __init__(self, records: List[Dict], tokenizer, max_length: int):
        self.records = records
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.records)

    def __getitem__(self, idx):
        rec = self.records[idx]
        enc = self.tokenizer(
            rec["ws_review"],
            truncation=True,
            max_length=self.max_length,
            padding="max_length",
            return_tensors="pt",
        )

        y_entity = torch.zeros(len(aspect2id), dtype=torch.float)
        for a in rec["aspects"]:
            if a in aspect2id:
                y_entity[aspect2id[a]] = 1.0

        y_aspect = torch.zeros(len(aspect_category2id), dtype=torch.float)
        for ac in rec["aspect_categories"]:
            if ac in aspect_category2id:
                y_aspect[aspect_category2id[ac]] = 1.0

        y_polarity = torch.full((len(aspect_category2id),), -100, dtype=torch.long)
        for ac, pol in rec["polarity_by_aspect_category"].items():
            if ac in aspect_category2id:
                y_polarity[aspect_category2id[ac]] = sentiment2id[normalize_sentiment(pol)]

        return {
            "input_ids": enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "y_entity": y_entity,
            "y_aspect": y_aspect,
            "y_polarity": y_polarity,
            "text": rec["ws_review"],
        }

train_dataset = ABSAHierDataset(train_records, tokenizer, MAX_LENGTH)
val_dataset = ABSAHierDataset(val_records, tokenizer, MAX_LENGTH)
test_dataset = ABSAHierDataset(test_records, tokenizer, MAX_LENGTH)

train_loader = DataLoader(train_dataset, batch_size=TRAIN_BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=EVAL_BATCH_SIZE, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=EVAL_BATCH_SIZE, shuffle=False)

print(len(train_dataset), len(val_dataset), len(test_dataset))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/557 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

2961 1290 500

In [11]:
class HierarchicalABSA(nn.Module):

    def __init__(self, model_name: str, n_entity: int, n_aspect: int, n_sentiment: int):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(model_name)
        hidden = self.encoder.config.hidden_size

        # entity 
        self.entity_head = nn.Linear(hidden, n_entity)
        self.entity_bridge = nn.Sequential(
            nn.Linear(n_entity, hidden * 2),
            nn.GELU(),
            nn.Linear(hidden * 2, hidden),
        )

        # aspect 
        self.aspect_head = nn.Linear(hidden * 2, n_aspect)
        self.aspect_bridge = nn.Sequential(
            nn.Linear(n_aspect, hidden * 2),
            nn.GELU(),
            nn.Linear(hidden * 2, hidden * 2)
        )

        # polarity
        self.polarity_head = nn.Linear(hidden * 3, n_aspect * n_sentiment)

        self.drop = nn.Dropout(0.1)
        self.n_aspect = n_aspect
        self.n_sentiment = n_sentiment

    def forward(self, input_ids, attention_mask):
        out = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        x = self.drop(out.last_hidden_state[:, 0, :])

        entity_logits = self.entity_head(x)
        entity_probs = torch.sigmoid(entity_logits)

        entity_ctx = self.entity_bridge(entity_probs)
        entity_ctx = entity_ctx + x
        h2 = torch.cat([x, entity_ctx], dim=-1)

        aspect_logits = self.aspect_head(h2)
        aspect_probs = torch.sigmoid(aspect_logits)
        aspect_ctx = self.aspect_bridge(aspect_probs)
        aspect_ctx = aspect_ctx + h2
        h3 = torch.cat([x, aspect_ctx], dim=-1)

        polarity_logits = self.polarity_head(h3).view(-1, self.n_aspect, self.n_sentiment)
        return {
            "entity_logits": entity_logits,
            "aspect_logits": aspect_logits,
            "polarity_logits": polarity_logits,
            "entity_probs": entity_probs,
            "aspect_probs": aspect_probs,
        }

ce_loss = nn.CrossEntropyLoss(ignore_index=-100)


def compute_global_loss(outputs, y_entity, y_aspect, y_polarity):
    l_entity = F.binary_cross_entropy_with_logits(outputs["entity_logits"], y_entity)
    l_aspect = F.binary_cross_entropy_with_logits(outputs["aspect_logits"], y_aspect)

    pol_logits = outputs["polarity_logits"].reshape(-1, len(SENTIMENT_SPACE))
    pol_target = y_polarity.reshape(-1)
    l_polarity = ce_loss(pol_logits, pol_target)

    entity_probs = outputs["entity_probs"]
    aspect_probs = outputs["aspect_probs"]
    
    total = (
        LOSS_WEIGHTS["entity"] * l_entity
        + LOSS_WEIGHTS["aspect"] * l_aspect
        + LOSS_WEIGHTS["polarity"] * l_polarity
    )

    return total, {
        "entity": l_entity.item(),
        "aspect": l_aspect.item(),
        "polarity": l_polarity.item(),
        "global": total.item(),
    }


def micro_f1_from_binary(y_true: torch.Tensor, y_pred: torch.Tensor, eps: float = 1e-9):

    tp = ((y_true == 1) & (y_pred == 1)).sum().item()

    fp = ((y_true == 0) & (y_pred == 1)).sum().item()

    fn = ((y_true == 1) & (y_pred == 0)).sum().item()

    precision = tp / (tp + fp + eps)

    recall = tp / (tp + fn + eps)

    f1 = 2 * precision * recall / (precision + recall + eps)

    return precision, recall, f1


def aspect_category_java_style_metrics(

    y_aspect: torch.Tensor,

    y_polarity: torch.Tensor,

    aspect_probs: torch.Tensor,

    polarity_logits: torch.Tensor,

    threshold_aspect: float = 0.5,

    eps: float = 1e-9,

) -> Dict[str, Dict[str, float]]:

    """Mirror SAEvaluate.java counting for Aspect#Category and Aspect#Category#Polarity."""

    aspect_true = y_aspect.long()

    aspect_pred = (aspect_probs >= threshold_aspect).long()

    pol_true = y_polarity.long()

    pol_pred = polarity_logits.argmax(dim=-1).long()

    total_gold = int((aspect_true == 1).sum().item())

    total_pred = int((aspect_pred == 1).sum().item())

    correct_aspect = int(((aspect_true == 1) & (aspect_pred == 1)).sum().item())

    correct_aspect_polarity = int(

        ((aspect_true == 1) & (aspect_pred == 1) & (pol_true != -100) & (pol_pred == pol_true)).sum().item()

    )

    p_aspect = correct_aspect / (total_pred + eps)

    r_aspect = correct_aspect / (total_gold + eps)

    f1_aspect = 2 * p_aspect * r_aspect / (p_aspect + r_aspect + eps)

    p_ap = correct_aspect_polarity / (total_pred + eps)

    r_ap = correct_aspect_polarity / (total_gold + eps)

    f1_ap = 2 * p_ap * r_ap / (p_ap + r_ap + eps)

    return {

        "aspect_category": {

            "precision": p_aspect,

            "recall": r_aspect,

            "micro_f1": f1_aspect,

            "correct": correct_aspect,

            "predicted": total_pred,

            "gold": total_gold,

        },

        "aspect_category_polarity": {

            "precision": p_ap,

            "recall": r_ap,

            "micro_f1": f1_ap,

            "correct": correct_aspect_polarity,

            "predicted": total_pred,

            "gold": total_gold,

        },

    }

In [12]:
def run_epoch(model, loader, optimizer=None, scheduler=None, train_mode=True):
    if train_mode:
        model.train()
    else:
        model.eval()

    scaler = torch.cuda.amp.GradScaler(enabled=torch.cuda.is_available() and train_mode)

    losses = []
    ent_true_all, ent_pred_all = [], []
    asp_true_all, asp_pred_all, asp_probs_all = [], [], []
    pol_logits_all, pol_true_all = [], []

    pbar = tqdm(loader, desc="train" if train_mode else "eval", leave=False)
    for batch in pbar:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        y_entity = batch["y_entity"].to(device)
        y_aspect = batch["y_aspect"].to(device)
        y_polarity = batch["y_polarity"].to(device)

        with torch.set_grad_enabled(train_mode):
            with torch.cuda.amp.autocast(enabled=torch.cuda.is_available() and train_mode):
                outputs = model(input_ids=input_ids, attention_mask=attention_mask)
                loss, loss_items = compute_global_loss(outputs, y_entity, y_aspect, y_polarity)

            if train_mode:
                optimizer.zero_grad(set_to_none=True)
                scaler.scale(loss).backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
                if scheduler is not None:
                    scheduler.step()

        losses.append(loss_items)

        ent_pred = (outputs["entity_probs"] >= THRESHOLD_ENTITY).long().detach().cpu()
        asp_pred = (outputs["aspect_probs"] >= THRESHOLD_ASPECT).long().detach().cpu()
        asp_probs = outputs["aspect_probs"].detach().cpu()
        ent_true = y_entity.long().detach().cpu()
        asp_true = y_aspect.long().detach().cpu()

        ent_true_all.append(ent_true)
        ent_pred_all.append(ent_pred)
        asp_true_all.append(asp_true)
        asp_pred_all.append(asp_pred)
        asp_probs_all.append(asp_probs)
        pol_logits_all.append(outputs["polarity_logits"].detach().cpu())
        pol_true_all.append(y_polarity.detach().cpu())

    avg_loss = {k: float(np.mean([x[k] for x in losses])) for k in losses[0].keys()}

    ent_true_cat = torch.cat(ent_true_all, dim=0)
    ent_pred_cat = torch.cat(ent_pred_all, dim=0)
    asp_true_cat = torch.cat(asp_true_all, dim=0)
    asp_pred_cat = torch.cat(asp_pred_all, dim=0)
    asp_probs_cat = torch.cat(asp_probs_all, dim=0)
    pol_logits_cat = torch.cat(pol_logits_all, dim=0)
    pol_true_cat = torch.cat(pol_true_all, dim=0)

    ent_p, ent_r, ent_f1 = micro_f1_from_binary(ent_true_cat, ent_pred_cat)
    asp_p, asp_r, asp_f1 = micro_f1_from_binary(asp_true_cat, asp_pred_cat)
    java_style = aspect_category_java_style_metrics(
        y_aspect=asp_true_cat,
        y_polarity=pol_true_cat,
        aspect_probs=asp_probs_cat,
        polarity_logits=pol_logits_cat,
        threshold_aspect=THRESHOLD_ASPECT,
    )

    metrics = {
        "loss": avg_loss,
        "entity": {"precision": ent_p, "recall": ent_r, "micro_f1": ent_f1},
        "aspect": {"precision": asp_p, "recall": asp_r, "micro_f1": asp_f1},
        "aspect_category": java_style["aspect_category"],
        "aspect_category_polarity": java_style["aspect_category_polarity"],
    }
    return metrics

In [13]:
model = HierarchicalABSA(
    model_name=MODEL_NAME,
    n_entity=len(aspect2id),
    n_aspect=len(aspect_category2id),
    n_sentiment=len(SENTIMENT_SPACE),
).to(device)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
)

num_training_steps = len(train_loader) * NUM_EPOCHS
num_warmup_steps = int(num_training_steps * WARMUP_RATIO)
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=num_warmup_steps,
    num_training_steps=num_training_steps,)

history = []
best_test_aspect_f1 = -1.0
best_epoch = -1
bad_epochs = 0

for epoch in range(1, NUM_EPOCHS + 1):
    train_metrics = run_epoch(model, train_loader, optimizer, scheduler, train_mode=True)
    # val_metrics = run_epoch(model, val_loader, train_mode=False)
    test_metrics = run_epoch(model, test_loader, train_mode=False)

    row = {
        "epoch": epoch,
        "train": train_metrics,
        # "val": val_metrics,
        "test": test_metrics,
    }
    history.append(row)

    # val_aspect_f1 = val_metrics["aspect"]["micro_f1"]
    # val_entity_f1 = val_metrics["entity"]["micro_f1"]
    # val_ac_polarity_f1 = val_metrics["aspect_category_polarity"]["micro_f1"]
    test_aspect_p = test_metrics["aspect"]["precision"]
    test_aspect_r = test_metrics["aspect"]["recall"]
    test_aspect_f1 = test_metrics["aspect"]["micro_f1"]

    test_entity_p = test_metrics["entity"]["precision"]
    test_entity_r = test_metrics["entity"]["recall"]
    test_entity_f1 = test_metrics["entity"]["micro_f1"]

    test_ac_polarity_p = test_metrics["aspect_category_polarity"]["precision"]
    test_ac_polarity_r = test_metrics["aspect_category_polarity"]["recall"]
    test_ac_polarity_f1 = test_metrics["aspect_category_polarity"]["micro_f1"]
    
    print(
        f"Epoch {epoch:02d} | train_global_loss={train_metrics['loss']['global']:.4f}\n"
        f"  [Entity]                   P: {test_entity_p:.4f} | R: {test_entity_r:.4f} | F1: {test_entity_f1:.4f}\n"
        f"  [Aspect#Category]          P: {test_aspect_p:.4f} | R: {test_aspect_r:.4f} | F1: {test_aspect_f1:.4f}\n"
        f"  [Aspect#Category#Polarity] P: {test_ac_polarity_p:.4f} | R: {test_ac_polarity_r:.4f} | F1: {test_ac_polarity_f1:.4f}\n"
        f"--------------------------------------------------------------------------------"
    )

    if test_aspect_f1 > best_test_aspect_f1:
        best_test_aspect_f1 = test_aspect_f1
        best_epoch = epoch
        bad_epochs = 0

        ckpt_dir = OUTPUT_DIR / "best_checkpoint"
        ckpt_dir.mkdir(parents=True, exist_ok=True)
        torch.save(model.state_dict(), ckpt_dir / "model.pt")
        tokenizer.save_pretrained(ckpt_dir)

        with open(ckpt_dir / "training_config.json", "w", encoding="utf-8") as f:
            json.dump({
                "model_name": MODEL_NAME,
                "max_length": MAX_LENGTH,
                "threshold_entity": THRESHOLD_ENTITY,
                "threshold_aspect": THRESHOLD_ASPECT,
                "loss_weights": LOSS_WEIGHTS,
                "best_epoch": best_epoch,
                "best_test_aspect_micro_f1": best_test_aspect_f1,
            }, f, ensure_ascii=False, indent=2)
    else:
        bad_epochs += 1
        if bad_epochs >= PATIENCE:
            print(f"Early stopping at epoch {epoch}")
            break

with open(OUTPUT_DIR / "history.json", "w", encoding="utf-8") as f:
    json.dump(history, f, ensure_ascii=False, indent=2)

print("Best epoch:", best_epoch)
print("Best test Aspect Micro-F1:", round(best_test_aspect_f1, 6))

pytorch_model.bin:   0%|          | 0.00/543M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/543M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: vinai/phobert-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |
lm_head.decoder.bias            | UNEXPECTED |  |
lm_head.dense.bias              | UNEXPECTED |  |
lm_head.dense.weight            | UNEXPECTED |  |
lm_head.layer_norm.bias         | UNEXPECTED |  |
lm_head.bias                    | UNEXPECTED |  |
lm_head.layer_norm.weight       | UNEXPECTED |  |
lm_head.decoder.weight          | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
/tmp/ipykernel_58/1399836253.py:7: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=torch.cuda.is_available() and train_mode)

train:   0%|          | 0/186 [00:00<?, ?it/s]

/tmp/ipykernel_58/1399836253.py:23: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=torch.cuda.is_available() and train_mode):

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 01 | train_global_loss=2.6127
  [Entity]                   P: 0.8000 | R: 0.7139 | F1: 0.7545
  [Aspect#Category]          P: 0.7610 | R: 0.6738 | F1: 0.7148
  [Aspect#Category#Polarity] P: 0.5896 | R: 0.5221 | F1: 0.5538
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 02 | train_global_loss=1.9715
  [Entity]                   P: 0.8696 | R: 0.7349 | F1: 0.7966
  [Aspect#Category]          P: 0.8463 | R: 0.6714 | F1: 0.7487
  [Aspect#Category#Polarity] P: 0.6899 | R: 0.5473 | F1: 0.6104
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 03 | train_global_loss=1.5313
  [Entity]                   P: 0.8720 | R: 0.8720 | F1: 0.8720
  [Aspect#Category]          P: 0.8402 | R: 0.7586 | F1: 0.7973
  [Aspect#Category#Polarity] P: 0.6818 | R: 0.6155 | F1: 0.6470
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 04 | train_global_loss=1.3081
  [Entity]                   P: 0.8425 | R: 0.8917 | F1: 0.8664
  [Aspect#Category]          P: 0.8117 | R: 0.8020 | F1: 0.8068
  [Aspect#Category#Polarity] P: 0.6720 | R: 0.6639 | F1: 0.6679
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 05 | train_global_loss=1.1617
  [Entity]                   P: 0.8652 | R: 0.8845 | F1: 0.8748
  [Aspect#Category]          P: 0.8415 | R: 0.7838 | F1: 0.8116
  [Aspect#Category#Polarity] P: 0.6840 | R: 0.6370 | F1: 0.6597
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 06 | train_global_loss=1.0519
  [Entity]                   P: 0.8963 | R: 0.8681 | F1: 0.8820
  [Aspect#Category]          P: 0.8623 | R: 0.7974 | F1: 0.8286
  [Aspect#Category#Polarity] P: 0.7179 | R: 0.6639 | F1: 0.6899
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 07 | train_global_loss=0.8755
  [Entity]                   P: 0.8570 | R: 0.9081 | F1: 0.8818
  [Aspect#Category]          P: 0.8334 | R: 0.8293 | F1: 0.8313
  [Aspect#Category#Polarity] P: 0.6984 | R: 0.6949 | F1: 0.6966
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 08 | train_global_loss=0.8097
  [Entity]                   P: 0.8764 | R: 0.9022 | F1: 0.8891
  [Aspect#Category]          P: 0.8445 | R: 0.8193 | F1: 0.8317
  [Aspect#Category#Polarity] P: 0.7073 | R: 0.6862 | F1: 0.6966
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 09 | train_global_loss=0.7387
  [Entity]                   P: 0.8912 | R: 0.8707 | F1: 0.8808
  [Aspect#Category]          P: 0.8637 | R: 0.7888 | F1: 0.8245
  [Aspect#Category#Polarity] P: 0.7248 | R: 0.6618 | F1: 0.6919
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 10 | train_global_loss=0.6819
  [Entity]                   P: 0.8977 | R: 0.8635 | F1: 0.8803
  [Aspect#Category]          P: 0.8629 | R: 0.8090 | F1: 0.8351
  [Aspect#Category#Polarity] P: 0.7218 | R: 0.6767 | F1: 0.6985
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 11 | train_global_loss=0.6206
  [Entity]                   P: 0.8699 | R: 0.9042 | F1: 0.8867
  [Aspect#Category]          P: 0.8465 | R: 0.8276 | F1: 0.8370
  [Aspect#Category#Polarity] P: 0.7163 | R: 0.7003 | F1: 0.7082
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 12 | train_global_loss=0.5930
  [Entity]                   P: 0.8578 | R: 0.9101 | F1: 0.8832
  [Aspect#Category]          P: 0.8259 | R: 0.8293 | F1: 0.8276
  [Aspect#Category#Polarity] P: 0.6995 | R: 0.7024 | F1: 0.7009
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 13 | train_global_loss=0.5360
  [Entity]                   P: 0.8805 | R: 0.8996 | F1: 0.8900
  [Aspect#Category]          P: 0.8451 | R: 0.8322 | F1: 0.8386
  [Aspect#Category#Polarity] P: 0.7217 | R: 0.7106 | F1: 0.7161
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 14 | train_global_loss=0.4808
  [Entity]                   P: 0.8804 | R: 0.9035 | F1: 0.8918
  [Aspect#Category]          P: 0.8407 | R: 0.8355 | F1: 0.8381
  [Aspect#Category#Polarity] P: 0.7142 | R: 0.7098 | F1: 0.7120
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 15 | train_global_loss=0.4371
  [Entity]                   P: 0.8581 | R: 0.9206 | F1: 0.8883
  [Aspect#Category]          P: 0.8248 | R: 0.8351 | F1: 0.8299
  [Aspect#Category#Polarity] P: 0.6942 | R: 0.7028 | F1: 0.6984
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 16 | train_global_loss=0.4005
  [Entity]                   P: 0.8916 | R: 0.9009 | F1: 0.8962
  [Aspect#Category]          P: 0.8488 | R: 0.8375 | F1: 0.8431
  [Aspect#Category#Polarity] P: 0.7227 | R: 0.7131 | F1: 0.7179
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 17 | train_global_loss=0.3729
  [Entity]                   P: 0.8685 | R: 0.9140 | F1: 0.8907
  [Aspect#Category]          P: 0.8278 | R: 0.8483 | F1: 0.8379
  [Aspect#Category#Polarity] P: 0.7007 | R: 0.7181 | F1: 0.7093
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 18 | train_global_loss=0.3359
  [Entity]                   P: 0.8981 | R: 0.8734 | F1: 0.8856
  [Aspect#Category]          P: 0.8510 | R: 0.8289 | F1: 0.8398
  [Aspect#Category#Polarity] P: 0.7194 | R: 0.7007 | F1: 0.7099
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 19 | train_global_loss=0.3052
  [Entity]                   P: 0.8818 | R: 0.9009 | F1: 0.8913
  [Aspect#Category]          P: 0.8356 | R: 0.8090 | F1: 0.8221
  [Aspect#Category#Polarity] P: 0.7152 | R: 0.6924 | F1: 0.7036
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 20 | train_global_loss=0.2805
  [Entity]                   P: 0.8780 | R: 0.9068 | F1: 0.8922
  [Aspect#Category]          P: 0.8381 | R: 0.8429 | F1: 0.8405
  [Aspect#Category#Polarity] P: 0.7180 | R: 0.7222 | F1: 0.7201
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 21 | train_global_loss=0.2552
  [Entity]                   P: 0.8822 | R: 0.8944 | F1: 0.8882
  [Aspect#Category]          P: 0.8376 | R: 0.8334 | F1: 0.8355
  [Aspect#Category#Polarity] P: 0.7175 | R: 0.7139 | F1: 0.7157
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 22 | train_global_loss=0.2450
  [Entity]                   P: 0.8753 | R: 0.9121 | F1: 0.8933
  [Aspect#Category]          P: 0.8126 | R: 0.8553 | F1: 0.8334
  [Aspect#Category#Polarity] P: 0.6917 | R: 0.7280 | F1: 0.7094
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 23 | train_global_loss=0.2230
  [Entity]                   P: 0.8715 | R: 0.9081 | F1: 0.8895
  [Aspect#Category]          P: 0.8316 | R: 0.8495 | F1: 0.8405
  [Aspect#Category#Polarity] P: 0.7139 | R: 0.7292 | F1: 0.7215
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 24 | train_global_loss=0.1988
  [Entity]                   P: 0.8767 | R: 0.9094 | F1: 0.8928
  [Aspect#Category]          P: 0.8339 | R: 0.8388 | F1: 0.8364
  [Aspect#Category#Polarity] P: 0.7115 | R: 0.7156 | F1: 0.7135
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 25 | train_global_loss=0.1764
  [Entity]                   P: 0.8810 | R: 0.9134 | F1: 0.8969
  [Aspect#Category]          P: 0.8340 | R: 0.8516 | F1: 0.8427
  [Aspect#Category#Polarity] P: 0.7170 | R: 0.7321 | F1: 0.7245
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 26 | train_global_loss=0.1567
  [Entity]                   P: 0.8861 | R: 0.8930 | F1: 0.8895
  [Aspect#Category]          P: 0.8417 | R: 0.8442 | F1: 0.8429
  [Aspect#Category#Polarity] P: 0.7222 | R: 0.7243 | F1: 0.7232
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 27 | train_global_loss=0.1515
  [Entity]                   P: 0.8840 | R: 0.9049 | F1: 0.8943
  [Aspect#Category]          P: 0.8414 | R: 0.8268 | F1: 0.8340
  [Aspect#Category#Polarity] P: 0.7244 | R: 0.7119 | F1: 0.7181
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 28 | train_global_loss=0.1363
  [Entity]                   P: 0.8817 | R: 0.9049 | F1: 0.8931
  [Aspect#Category]          P: 0.8376 | R: 0.8231 | F1: 0.8303
  [Aspect#Category#Polarity] P: 0.7228 | R: 0.7102 | F1: 0.7164
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 29 | train_global_loss=0.1251
  [Entity]                   P: 0.8835 | R: 0.9055 | F1: 0.8944
  [Aspect#Category]          P: 0.8379 | R: 0.8400 | F1: 0.8390
  [Aspect#Category#Polarity] P: 0.7212 | R: 0.7230 | F1: 0.7221
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 30 | train_global_loss=0.1151
  [Entity]                   P: 0.8861 | R: 0.9088 | F1: 0.8973
  [Aspect#Category]          P: 0.8400 | R: 0.8396 | F1: 0.8398
  [Aspect#Category#Polarity] P: 0.7229 | R: 0.7226 | F1: 0.7228
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 31 | train_global_loss=0.1086
  [Entity]                   P: 0.8626 | R: 0.9186 | F1: 0.8897
  [Aspect#Category]          P: 0.8248 | R: 0.8408 | F1: 0.8328
  [Aspect#Category#Polarity] P: 0.7157 | R: 0.7296 | F1: 0.7226
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 32 | train_global_loss=0.1001
  [Entity]                   P: 0.8633 | R: 0.9160 | F1: 0.8889
  [Aspect#Category]          P: 0.8254 | R: 0.8582 | F1: 0.8415
  [Aspect#Category#Polarity] P: 0.7093 | R: 0.7375 | F1: 0.7231
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 33 | train_global_loss=0.0951
  [Entity]                   P: 0.8714 | R: 0.9206 | F1: 0.8953
  [Aspect#Category]          P: 0.8279 | R: 0.8491 | F1: 0.8384
  [Aspect#Category#Polarity] P: 0.7110 | R: 0.7292 | F1: 0.7200
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 34 | train_global_loss=0.0847
  [Entity]                   P: 0.8841 | R: 0.8963 | F1: 0.8902
  [Aspect#Category]          P: 0.8361 | R: 0.8475 | F1: 0.8417
  [Aspect#Category#Polarity] P: 0.7186 | R: 0.7284 | F1: 0.7235
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 35 | train_global_loss=0.0790
  [Entity]                   P: 0.8788 | R: 0.9042 | F1: 0.8913
  [Aspect#Category]          P: 0.8354 | R: 0.8413 | F1: 0.8383
  [Aspect#Category#Polarity] P: 0.7147 | R: 0.7197 | F1: 0.7172
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 36 | train_global_loss=0.0731
  [Entity]                   P: 0.8801 | R: 0.9154 | F1: 0.8974
  [Aspect#Category]          P: 0.8345 | R: 0.8611 | F1: 0.8476
  [Aspect#Category#Polarity] P: 0.7147 | R: 0.7375 | F1: 0.7259
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 37 | train_global_loss=0.0712
  [Entity]                   P: 0.8706 | R: 0.9140 | F1: 0.8918
  [Aspect#Category]          P: 0.8285 | R: 0.8628 | F1: 0.8453
  [Aspect#Category#Polarity] P: 0.7122 | R: 0.7416 | F1: 0.7266
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 38 | train_global_loss=0.0613
  [Entity]                   P: 0.8737 | R: 0.9081 | F1: 0.8906
  [Aspect#Category]          P: 0.8325 | R: 0.8446 | F1: 0.8385
  [Aspect#Category#Polarity] P: 0.7115 | R: 0.7218 | F1: 0.7166
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 39 | train_global_loss=0.0584
  [Entity]                   P: 0.8698 | R: 0.9206 | F1: 0.8945
  [Aspect#Category]          P: 0.8241 | R: 0.8599 | F1: 0.8416
  [Aspect#Category#Polarity] P: 0.7100 | R: 0.7408 | F1: 0.7251
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 40 | train_global_loss=0.0587
  [Entity]                   P: 0.8596 | R: 0.9278 | F1: 0.8924
  [Aspect#Category]          P: 0.8225 | R: 0.8661 | F1: 0.8437
  [Aspect#Category#Polarity] P: 0.7067 | R: 0.7441 | F1: 0.7249
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 41 | train_global_loss=0.0494
  [Entity]                   P: 0.8752 | R: 0.9160 | F1: 0.8952
  [Aspect#Category]          P: 0.8331 | R: 0.8499 | F1: 0.8414
  [Aspect#Category#Polarity] P: 0.7196 | R: 0.7342 | F1: 0.7268
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 42 | train_global_loss=0.0468
  [Entity]                   P: 0.8760 | R: 0.9134 | F1: 0.8943
  [Aspect#Category]          P: 0.8306 | R: 0.8615 | F1: 0.8458
  [Aspect#Category#Polarity] P: 0.7098 | R: 0.7363 | F1: 0.7228
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 43 | train_global_loss=0.0438
  [Entity]                   P: 0.8656 | R: 0.9252 | F1: 0.8944
  [Aspect#Category]          P: 0.8130 | R: 0.8644 | F1: 0.8379
  [Aspect#Category#Polarity] P: 0.7026 | R: 0.7470 | F1: 0.7241
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 44 | train_global_loss=0.0428
  [Entity]                   P: 0.8812 | R: 0.9003 | F1: 0.8906
  [Aspect#Category]          P: 0.8318 | R: 0.8487 | F1: 0.8402
  [Aspect#Category#Polarity] P: 0.7180 | R: 0.7325 | F1: 0.7252
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 45 | train_global_loss=0.0387
  [Entity]                   P: 0.8770 | R: 0.9127 | F1: 0.8945
  [Aspect#Category]          P: 0.8348 | R: 0.8566 | F1: 0.8455
  [Aspect#Category#Polarity] P: 0.7232 | R: 0.7420 | F1: 0.7325
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 46 | train_global_loss=0.0343
  [Entity]                   P: 0.8725 | R: 0.9206 | F1: 0.8959
  [Aspect#Category]          P: 0.8240 | R: 0.8690 | F1: 0.8459
  [Aspect#Category#Polarity] P: 0.7142 | R: 0.7532 | F1: 0.7332
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 47 | train_global_loss=0.0342
  [Entity]                   P: 0.8898 | R: 0.8950 | F1: 0.8924
  [Aspect#Category]          P: 0.8374 | R: 0.8367 | F1: 0.8371
  [Aspect#Category#Polarity] P: 0.7216 | R: 0.7210 | F1: 0.7213
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 48 | train_global_loss=0.0319
  [Entity]                   P: 0.8695 | R: 0.9134 | F1: 0.8909
  [Aspect#Category]          P: 0.8214 | R: 0.8648 | F1: 0.8425
  [Aspect#Category#Polarity] P: 0.7126 | R: 0.7503 | F1: 0.7310
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 49 | train_global_loss=0.0331
  [Entity]                   P: 0.8678 | R: 0.9259 | F1: 0.8959
  [Aspect#Category]          P: 0.8188 | R: 0.8520 | F1: 0.8351
  [Aspect#Category#Polarity] P: 0.7088 | R: 0.7375 | F1: 0.7229
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 50 | train_global_loss=0.0273
  [Entity]                   P: 0.8783 | R: 0.9094 | F1: 0.8936
  [Aspect#Category]          P: 0.8311 | R: 0.8623 | F1: 0.8464
  [Aspect#Category#Polarity] P: 0.7223 | R: 0.7495 | F1: 0.7356
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 51 | train_global_loss=0.0263
  [Entity]                   P: 0.8803 | R: 0.9075 | F1: 0.8937
  [Aspect#Category]          P: 0.8303 | R: 0.8599 | F1: 0.8448
  [Aspect#Category#Polarity] P: 0.7166 | R: 0.7420 | F1: 0.7291
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 52 | train_global_loss=0.0249
  [Entity]                   P: 0.8818 | R: 0.9154 | F1: 0.8983
  [Aspect#Category]          P: 0.8255 | R: 0.8681 | F1: 0.8463
  [Aspect#Category#Polarity] P: 0.7138 | R: 0.7507 | F1: 0.7318
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 53 | train_global_loss=0.0236
  [Entity]                   P: 0.8856 | R: 0.8937 | F1: 0.8896
  [Aspect#Category]          P: 0.8379 | R: 0.8417 | F1: 0.8398
  [Aspect#Category#Polarity] P: 0.7243 | R: 0.7276 | F1: 0.7259
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 54 | train_global_loss=0.0223
  [Entity]                   P: 0.8618 | R: 0.9285 | F1: 0.8939
  [Aspect#Category]          P: 0.8155 | R: 0.8644 | F1: 0.8393
  [Aspect#Category#Polarity] P: 0.6989 | R: 0.7408 | F1: 0.7192
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 55 | train_global_loss=0.0204
  [Entity]                   P: 0.8839 | R: 0.9094 | F1: 0.8965
  [Aspect#Category]          P: 0.8410 | R: 0.8487 | F1: 0.8449
  [Aspect#Category#Polarity] P: 0.7284 | R: 0.7350 | F1: 0.7317
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 56 | train_global_loss=0.0188
  [Entity]                   P: 0.8973 | R: 0.8885 | F1: 0.8928
  [Aspect#Category]          P: 0.8510 | R: 0.8359 | F1: 0.8434
  [Aspect#Category#Polarity] P: 0.7391 | R: 0.7259 | F1: 0.7324
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 57 | train_global_loss=0.0201
  [Entity]                   P: 0.8774 | R: 0.9160 | F1: 0.8963
  [Aspect#Category]          P: 0.8317 | R: 0.8603 | F1: 0.8458
  [Aspect#Category#Polarity] P: 0.7190 | R: 0.7437 | F1: 0.7312
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 58 | train_global_loss=0.0178
  [Entity]                   P: 0.8749 | R: 0.9180 | F1: 0.8959
  [Aspect#Category]          P: 0.8292 | R: 0.8648 | F1: 0.8466
  [Aspect#Category#Polarity] P: 0.7170 | R: 0.7478 | F1: 0.7321
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 59 | train_global_loss=0.0171
  [Entity]                   P: 0.8730 | R: 0.9199 | F1: 0.8958
  [Aspect#Category]          P: 0.8301 | R: 0.8566 | F1: 0.8431
  [Aspect#Category#Polarity] P: 0.7208 | R: 0.7437 | F1: 0.7320
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 60 | train_global_loss=0.0153
  [Entity]                   P: 0.8721 | R: 0.9219 | F1: 0.8963
  [Aspect#Category]          P: 0.8277 | R: 0.8599 | F1: 0.8435
  [Aspect#Category#Polarity] P: 0.7135 | R: 0.7412 | F1: 0.7271
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 61 | train_global_loss=0.0149
  [Entity]                   P: 0.8868 | R: 0.9094 | F1: 0.8980
  [Aspect#Category]          P: 0.8420 | R: 0.8528 | F1: 0.8474
  [Aspect#Category#Polarity] P: 0.7310 | R: 0.7404 | F1: 0.7357
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 62 | train_global_loss=0.0155
  [Entity]                   P: 0.8761 | R: 0.9186 | F1: 0.8969
  [Aspect#Category]          P: 0.8319 | R: 0.8553 | F1: 0.8435
  [Aspect#Category#Polarity] P: 0.7193 | R: 0.7396 | F1: 0.7293
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 63 | train_global_loss=0.0165
  [Entity]                   P: 0.8781 | R: 0.9121 | F1: 0.8948
  [Aspect#Category]          P: 0.8345 | R: 0.8566 | F1: 0.8454
  [Aspect#Category#Polarity] P: 0.7177 | R: 0.7367 | F1: 0.7271
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 64 | train_global_loss=0.0173
  [Entity]                   P: 0.8790 | R: 0.9101 | F1: 0.8943
  [Aspect#Category]          P: 0.8302 | R: 0.8648 | F1: 0.8471
  [Aspect#Category#Polarity] P: 0.7139 | R: 0.7437 | F1: 0.7285
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 65 | train_global_loss=0.0136
  [Entity]                   P: 0.8802 | R: 0.9114 | F1: 0.8956
  [Aspect#Category]          P: 0.8328 | R: 0.8566 | F1: 0.8445
  [Aspect#Category#Polarity] P: 0.7178 | R: 0.7383 | F1: 0.7279
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 66 | train_global_loss=0.0120
  [Entity]                   P: 0.8780 | R: 0.9114 | F1: 0.8944
  [Aspect#Category]          P: 0.8345 | R: 0.8611 | F1: 0.8476
  [Aspect#Category#Polarity] P: 0.7228 | R: 0.7458 | F1: 0.7341
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 67 | train_global_loss=0.0113
  [Entity]                   P: 0.8766 | R: 0.9134 | F1: 0.8946
  [Aspect#Category]          P: 0.8241 | R: 0.8698 | F1: 0.8463
  [Aspect#Category#Polarity] P: 0.7160 | R: 0.7557 | F1: 0.7353
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 68 | train_global_loss=0.0104
  [Entity]                   P: 0.8771 | R: 0.9134 | F1: 0.8949
  [Aspect#Category]          P: 0.8307 | R: 0.8437 | F1: 0.8372
  [Aspect#Category#Polarity] P: 0.7184 | R: 0.7296 | F1: 0.7240
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 69 | train_global_loss=0.0104
  [Entity]                   P: 0.8691 | R: 0.9232 | F1: 0.8953
  [Aspect#Category]          P: 0.8211 | R: 0.8690 | F1: 0.8443
  [Aspect#Category#Polarity] P: 0.7113 | R: 0.7528 | F1: 0.7315
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 70 | train_global_loss=0.0121
  [Entity]                   P: 0.8748 | R: 0.9173 | F1: 0.8956
  [Aspect#Category]          P: 0.8305 | R: 0.8611 | F1: 0.8455
  [Aspect#Category#Polarity] P: 0.7157 | R: 0.7420 | F1: 0.7286
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 71 | train_global_loss=0.0093
  [Entity]                   P: 0.8765 | R: 0.9081 | F1: 0.8920
  [Aspect#Category]          P: 0.8245 | R: 0.8640 | F1: 0.8438
  [Aspect#Category#Polarity] P: 0.7108 | R: 0.7449 | F1: 0.7275
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 72 | train_global_loss=0.0091
  [Entity]                   P: 0.8748 | R: 0.9167 | F1: 0.8952
  [Aspect#Category]          P: 0.8264 | R: 0.8656 | F1: 0.8455
  [Aspect#Category#Polarity] P: 0.7139 | R: 0.7478 | F1: 0.7305
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 73 | train_global_loss=0.0091
  [Entity]                   P: 0.8787 | R: 0.9127 | F1: 0.8954
  [Aspect#Category]          P: 0.8350 | R: 0.8640 | F1: 0.8492
  [Aspect#Category#Polarity] P: 0.7199 | R: 0.7449 | F1: 0.7322
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 74 | train_global_loss=0.0089
  [Entity]                   P: 0.8789 | R: 0.9140 | F1: 0.8961
  [Aspect#Category]          P: 0.8356 | R: 0.8636 | F1: 0.8494
  [Aspect#Category#Polarity] P: 0.7236 | R: 0.7478 | F1: 0.7355
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 75 | train_global_loss=0.0082
  [Entity]                   P: 0.8752 | R: 0.9108 | F1: 0.8926
  [Aspect#Category]          P: 0.8283 | R: 0.8677 | F1: 0.8476
  [Aspect#Category#Polarity] P: 0.7147 | R: 0.7487 | F1: 0.7313
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 76 | train_global_loss=0.0080
  [Entity]                   P: 0.8792 | R: 0.9075 | F1: 0.8931
  [Aspect#Category]          P: 0.8343 | R: 0.8512 | F1: 0.8426
  [Aspect#Category#Polarity] P: 0.7204 | R: 0.7350 | F1: 0.7276
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 77 | train_global_loss=0.0075
  [Entity]                   P: 0.8705 | R: 0.9173 | F1: 0.8933
  [Aspect#Category]          P: 0.8244 | R: 0.8615 | F1: 0.8425
  [Aspect#Category#Polarity] P: 0.7077 | R: 0.7396 | F1: 0.7233
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 78 | train_global_loss=0.0082
  [Entity]                   P: 0.8676 | R: 0.9160 | F1: 0.8912
  [Aspect#Category]          P: 0.8195 | R: 0.8561 | F1: 0.8374
  [Aspect#Category#Polarity] P: 0.7056 | R: 0.7371 | F1: 0.7210
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 79 | train_global_loss=0.0071
  [Entity]                   P: 0.8774 | R: 0.9114 | F1: 0.8941
  [Aspect#Category]          P: 0.8311 | R: 0.8648 | F1: 0.8476
  [Aspect#Category#Polarity] P: 0.7183 | R: 0.7474 | F1: 0.7326
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 80 | train_global_loss=0.0070
  [Entity]                   P: 0.8773 | R: 0.9101 | F1: 0.8934
  [Aspect#Category]          P: 0.8272 | R: 0.8590 | F1: 0.8428
  [Aspect#Category#Polarity] P: 0.7154 | R: 0.7429 | F1: 0.7289
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 81 | train_global_loss=0.0078
  [Entity]                   P: 0.8628 | R: 0.9199 | F1: 0.8904
  [Aspect#Category]          P: 0.8194 | R: 0.8702 | F1: 0.8440
  [Aspect#Category#Polarity] P: 0.7131 | R: 0.7573 | F1: 0.7346
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 82 | train_global_loss=0.0074
  [Entity]                   P: 0.8642 | R: 0.9226 | F1: 0.8924
  [Aspect#Category]          P: 0.8203 | R: 0.8756 | F1: 0.8470
  [Aspect#Category#Polarity] P: 0.7111 | R: 0.7590 | F1: 0.7343
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 83 | train_global_loss=0.0065
  [Entity]                   P: 0.8699 | R: 0.9213 | F1: 0.8948
  [Aspect#Category]          P: 0.8285 | R: 0.8710 | F1: 0.8493
  [Aspect#Category#Polarity] P: 0.7157 | R: 0.7524 | F1: 0.7336
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 84 | train_global_loss=0.0068
  [Entity]                   P: 0.8803 | R: 0.9121 | F1: 0.8959
  [Aspect#Category]          P: 0.8347 | R: 0.8685 | F1: 0.8513
  [Aspect#Category#Polarity] P: 0.7223 | R: 0.7516 | F1: 0.7366
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 85 | train_global_loss=0.0069
  [Entity]                   P: 0.8799 | R: 0.9134 | F1: 0.8963
  [Aspect#Category]          P: 0.8287 | R: 0.8640 | F1: 0.8460
  [Aspect#Category#Polarity] P: 0.7169 | R: 0.7474 | F1: 0.7318
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 86 | train_global_loss=0.0056
  [Entity]                   P: 0.8724 | R: 0.9193 | F1: 0.8952
  [Aspect#Category]          P: 0.8253 | R: 0.8747 | F1: 0.8493
  [Aspect#Category#Polarity] P: 0.7122 | R: 0.7549 | F1: 0.7329
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 87 | train_global_loss=0.0061
  [Entity]                   P: 0.8656 | R: 0.9259 | F1: 0.8947
  [Aspect#Category]          P: 0.8222 | R: 0.8718 | F1: 0.8463
  [Aspect#Category#Polarity] P: 0.7107 | R: 0.7536 | F1: 0.7315
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 88 | train_global_loss=0.0062
  [Entity]                   P: 0.8788 | R: 0.9088 | F1: 0.8935
  [Aspect#Category]          P: 0.8341 | R: 0.8607 | F1: 0.8472
  [Aspect#Category#Polarity] P: 0.7224 | R: 0.7453 | F1: 0.7337
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 89 | train_global_loss=0.0061
  [Entity]                   P: 0.8707 | R: 0.9232 | F1: 0.8962
  [Aspect#Category]          P: 0.8237 | R: 0.8690 | F1: 0.8457
  [Aspect#Category#Polarity] P: 0.7147 | R: 0.7540 | F1: 0.7339
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 90 | train_global_loss=0.0062
  [Entity]                   P: 0.8824 | R: 0.9062 | F1: 0.8941
  [Aspect#Category]          P: 0.8299 | R: 0.8570 | F1: 0.8432
  [Aspect#Category#Polarity] P: 0.7238 | R: 0.7474 | F1: 0.7354
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 91 | train_global_loss=0.0056
  [Entity]                   P: 0.8632 | R: 0.9278 | F1: 0.8944
  [Aspect#Category]          P: 0.8173 | R: 0.8690 | F1: 0.8423
  [Aspect#Category#Polarity] P: 0.7092 | R: 0.7540 | F1: 0.7309
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 92 | train_global_loss=0.0068
  [Entity]                   P: 0.8656 | R: 0.9167 | F1: 0.8904
  [Aspect#Category]          P: 0.8230 | R: 0.8685 | F1: 0.8451
  [Aspect#Category#Polarity] P: 0.7043 | R: 0.7433 | F1: 0.7233
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 93 | train_global_loss=0.0053
  [Entity]                   P: 0.8637 | R: 0.9272 | F1: 0.8943
  [Aspect#Category]          P: 0.8175 | R: 0.8776 | F1: 0.8465
  [Aspect#Category#Polarity] P: 0.7066 | R: 0.7586 | F1: 0.7317
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 94 | train_global_loss=0.0058
  [Entity]                   P: 0.8709 | R: 0.9206 | F1: 0.8951
  [Aspect#Category]          P: 0.8272 | R: 0.8768 | F1: 0.8513
  [Aspect#Category#Polarity] P: 0.7176 | R: 0.7606 | F1: 0.7385
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 95 | train_global_loss=0.0052
  [Entity]                   P: 0.8741 | R: 0.9199 | F1: 0.8964
  [Aspect#Category]          P: 0.8247 | R: 0.8694 | F1: 0.8464
  [Aspect#Category#Polarity] P: 0.7145 | R: 0.7532 | F1: 0.7333
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 96 | train_global_loss=0.0054
  [Entity]                   P: 0.8697 | R: 0.9154 | F1: 0.8919
  [Aspect#Category]          P: 0.8257 | R: 0.8752 | F1: 0.8497
  [Aspect#Category#Polarity] P: 0.7153 | R: 0.7582 | F1: 0.7361
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 97 | train_global_loss=0.0053
  [Entity]                   P: 0.8721 | R: 0.9173 | F1: 0.8941
  [Aspect#Category]          P: 0.8272 | R: 0.8706 | F1: 0.8483
  [Aspect#Category#Polarity] P: 0.7188 | R: 0.7565 | F1: 0.7372
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 98 | train_global_loss=0.0051
  [Entity]                   P: 0.8703 | R: 0.9206 | F1: 0.8948
  [Aspect#Category]          P: 0.8244 | R: 0.8694 | F1: 0.8463
  [Aspect#Category#Polarity] P: 0.7150 | R: 0.7540 | F1: 0.7340
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 99 | train_global_loss=0.0051
  [Entity]                   P: 0.8728 | R: 0.9232 | F1: 0.8973
  [Aspect#Category]          P: 0.8291 | R: 0.8685 | F1: 0.8484
  [Aspect#Category#Polarity] P: 0.7174 | R: 0.7516 | F1: 0.7341
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 100 | train_global_loss=0.0058
  [Entity]                   P: 0.8688 | R: 0.9213 | F1: 0.8943
  [Aspect#Category]          P: 0.8240 | R: 0.8669 | F1: 0.8449
  [Aspect#Category#Polarity] P: 0.7120 | R: 0.7491 | F1: 0.7301
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 101 | train_global_loss=0.0052
  [Entity]                   P: 0.8767 | R: 0.9140 | F1: 0.8950
  [Aspect#Category]          P: 0.8310 | R: 0.8656 | F1: 0.8479
  [Aspect#Category#Polarity] P: 0.7167 | R: 0.7466 | F1: 0.7313
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 102 | train_global_loss=0.0050
  [Entity]                   P: 0.8741 | R: 0.9199 | F1: 0.8964
  [Aspect#Category]          P: 0.8283 | R: 0.8698 | F1: 0.8486
  [Aspect#Category#Polarity] P: 0.7189 | R: 0.7549 | F1: 0.7364
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 103 | train_global_loss=0.0046
  [Entity]                   P: 0.8658 | R: 0.9232 | F1: 0.8936
  [Aspect#Category]          P: 0.8252 | R: 0.8648 | F1: 0.8446
  [Aspect#Category#Polarity] P: 0.7160 | R: 0.7503 | F1: 0.7327
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 104 | train_global_loss=0.0049
  [Entity]                   P: 0.8708 | R: 0.9245 | F1: 0.8969
  [Aspect#Category]          P: 0.8238 | R: 0.8640 | F1: 0.8434
  [Aspect#Category#Polarity] P: 0.7154 | R: 0.7503 | F1: 0.7324
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 105 | train_global_loss=0.0047
  [Entity]                   P: 0.8727 | R: 0.9173 | F1: 0.8944
  [Aspect#Category]          P: 0.8280 | R: 0.8677 | F1: 0.8474
  [Aspect#Category#Polarity] P: 0.7168 | R: 0.7511 | F1: 0.7335
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 106 | train_global_loss=0.0044
  [Entity]                   P: 0.8773 | R: 0.9147 | F1: 0.8956
  [Aspect#Category]          P: 0.8317 | R: 0.8681 | F1: 0.8495
  [Aspect#Category#Polarity] P: 0.7196 | R: 0.7511 | F1: 0.7350
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 107 | train_global_loss=0.0053
  [Entity]                   P: 0.8761 | R: 0.9186 | F1: 0.8969
  [Aspect#Category]          P: 0.8335 | R: 0.8690 | F1: 0.8508
  [Aspect#Category#Polarity] P: 0.7244 | R: 0.7553 | F1: 0.7395
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 108 | train_global_loss=0.0047
  [Entity]                   P: 0.8739 | R: 0.9232 | F1: 0.8979
  [Aspect#Category]          P: 0.8290 | R: 0.8760 | F1: 0.8519
  [Aspect#Category#Polarity] P: 0.7183 | R: 0.7590 | F1: 0.7381
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 109 | train_global_loss=0.0046
  [Entity]                   P: 0.8744 | R: 0.9226 | F1: 0.8978
  [Aspect#Category]          P: 0.8290 | R: 0.8698 | F1: 0.8489
  [Aspect#Category#Polarity] P: 0.7203 | R: 0.7557 | F1: 0.7375
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 110 | train_global_loss=0.0041
  [Entity]                   P: 0.8816 | R: 0.9134 | F1: 0.8972
  [Aspect#Category]          P: 0.8334 | R: 0.8623 | F1: 0.8476
  [Aspect#Category#Polarity] P: 0.7243 | R: 0.7495 | F1: 0.7367
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 111 | train_global_loss=0.0045
  [Entity]                   P: 0.8757 | R: 0.9199 | F1: 0.8973
  [Aspect#Category]          P: 0.8321 | R: 0.8669 | F1: 0.8492
  [Aspect#Category#Polarity] P: 0.7242 | R: 0.7544 | F1: 0.7390
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 112 | train_global_loss=0.0045
  [Entity]                   P: 0.8710 | R: 0.9213 | F1: 0.8954
  [Aspect#Category]          P: 0.8241 | R: 0.8756 | F1: 0.8491
  [Aspect#Category#Polarity] P: 0.7105 | R: 0.7549 | F1: 0.7320
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 113 | train_global_loss=0.0041
  [Entity]                   P: 0.8753 | R: 0.9213 | F1: 0.8977
  [Aspect#Category]          P: 0.8265 | R: 0.8743 | F1: 0.8497
  [Aspect#Category#Polarity] P: 0.7171 | R: 0.7586 | F1: 0.7372
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 114 | train_global_loss=0.0049
  [Entity]                   P: 0.8686 | R: 0.9239 | F1: 0.8954
  [Aspect#Category]          P: 0.8254 | R: 0.8714 | F1: 0.8478
  [Aspect#Category#Polarity] P: 0.7169 | R: 0.7569 | F1: 0.7364
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 115 | train_global_loss=0.0042
  [Entity]                   P: 0.8707 | R: 0.9193 | F1: 0.8944
  [Aspect#Category]          P: 0.8294 | R: 0.8681 | F1: 0.8483
  [Aspect#Category#Polarity] P: 0.7212 | R: 0.7549 | F1: 0.7376
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 116 | train_global_loss=0.0040
  [Entity]                   P: 0.8780 | R: 0.9160 | F1: 0.8966
  [Aspect#Category]          P: 0.8325 | R: 0.8690 | F1: 0.8503
  [Aspect#Category#Polarity] P: 0.7228 | R: 0.7544 | F1: 0.7383
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 117 | train_global_loss=0.0041
  [Entity]                   P: 0.8703 | R: 0.9199 | F1: 0.8944
  [Aspect#Category]          P: 0.8282 | R: 0.8752 | F1: 0.8511
  [Aspect#Category#Polarity] P: 0.7187 | R: 0.7594 | F1: 0.7385
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 118 | train_global_loss=0.0039
  [Entity]                   P: 0.8754 | R: 0.9173 | F1: 0.8959
  [Aspect#Category]          P: 0.8274 | R: 0.8681 | F1: 0.8473
  [Aspect#Category#Polarity] P: 0.7147 | R: 0.7499 | F1: 0.7319
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 119 | train_global_loss=0.0040
  [Entity]                   P: 0.8701 | R: 0.9186 | F1: 0.8937
  [Aspect#Category]          P: 0.8275 | R: 0.8743 | F1: 0.8503
  [Aspect#Category#Polarity] P: 0.7152 | R: 0.7557 | F1: 0.7349
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 120 | train_global_loss=0.0033
  [Entity]                   P: 0.8734 | R: 0.9147 | F1: 0.8936
  [Aspect#Category]          P: 0.8276 | R: 0.8710 | F1: 0.8487
  [Aspect#Category#Polarity] P: 0.7196 | R: 0.7573 | F1: 0.7380
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 121 | train_global_loss=0.0035
  [Entity]                   P: 0.8761 | R: 0.9140 | F1: 0.8947
  [Aspect#Category]          P: 0.8316 | R: 0.8677 | F1: 0.8493
  [Aspect#Category#Polarity] P: 0.7211 | R: 0.7524 | F1: 0.7364
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 122 | train_global_loss=0.0035
  [Entity]                   P: 0.8727 | R: 0.9173 | F1: 0.8944
  [Aspect#Category]          P: 0.8295 | R: 0.8685 | F1: 0.8485
  [Aspect#Category#Polarity] P: 0.7197 | R: 0.7536 | F1: 0.7363
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 123 | train_global_loss=0.0038
  [Entity]                   P: 0.8735 | R: 0.9199 | F1: 0.8961
  [Aspect#Category]          P: 0.8296 | R: 0.8632 | F1: 0.8460
  [Aspect#Category#Polarity] P: 0.7207 | R: 0.7499 | F1: 0.7350
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 124 | train_global_loss=0.0036
  [Entity]                   P: 0.8748 | R: 0.9173 | F1: 0.8956
  [Aspect#Category]          P: 0.8273 | R: 0.8694 | F1: 0.8478
  [Aspect#Category#Polarity] P: 0.7195 | R: 0.7561 | F1: 0.7374
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 125 | train_global_loss=0.0039
  [Entity]                   P: 0.8677 | R: 0.9206 | F1: 0.8933
  [Aspect#Category]          P: 0.8230 | R: 0.8764 | F1: 0.8488
  [Aspect#Category#Polarity] P: 0.7139 | R: 0.7602 | F1: 0.7363
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 126 | train_global_loss=0.0040
  [Entity]                   P: 0.8679 | R: 0.9226 | F1: 0.8944
  [Aspect#Category]          P: 0.8225 | R: 0.8772 | F1: 0.8490
  [Aspect#Category#Polarity] P: 0.7120 | R: 0.7594 | F1: 0.7349
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 127 | train_global_loss=0.0040
  [Entity]                   P: 0.8736 | R: 0.9160 | F1: 0.8943
  [Aspect#Category]          P: 0.8283 | R: 0.8677 | F1: 0.8476
  [Aspect#Category#Polarity] P: 0.7167 | R: 0.7507 | F1: 0.7333
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 128 | train_global_loss=0.0034
  [Entity]                   P: 0.8729 | R: 0.9193 | F1: 0.8955
  [Aspect#Category]          P: 0.8273 | R: 0.8714 | F1: 0.8488
  [Aspect#Category#Polarity] P: 0.7174 | R: 0.7557 | F1: 0.7361
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 129 | train_global_loss=0.0038
  [Entity]                   P: 0.8741 | R: 0.9160 | F1: 0.8946
  [Aspect#Category]          P: 0.8275 | R: 0.8648 | F1: 0.8458
  [Aspect#Category#Polarity] P: 0.7176 | R: 0.7499 | F1: 0.7334
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 130 | train_global_loss=0.0035
  [Entity]                   P: 0.8717 | R: 0.9186 | F1: 0.8946
  [Aspect#Category]          P: 0.8260 | R: 0.8735 | F1: 0.8491
  [Aspect#Category#Polarity] P: 0.7170 | R: 0.7582 | F1: 0.7370
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 131 | train_global_loss=0.0038
  [Entity]                   P: 0.8716 | R: 0.9173 | F1: 0.8939
  [Aspect#Category]          P: 0.8298 | R: 0.8706 | F1: 0.8497
  [Aspect#Category#Polarity] P: 0.7226 | R: 0.7582 | F1: 0.7400
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 132 | train_global_loss=0.0040
  [Entity]                   P: 0.8752 | R: 0.9160 | F1: 0.8952
  [Aspect#Category]          P: 0.8295 | R: 0.8690 | F1: 0.8488
  [Aspect#Category#Polarity] P: 0.7202 | R: 0.7544 | F1: 0.7369
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 133 | train_global_loss=0.0040
  [Entity]                   P: 0.8699 | R: 0.9173 | F1: 0.8930
  [Aspect#Category]          P: 0.8280 | R: 0.8694 | F1: 0.8482
  [Aspect#Category#Polarity] P: 0.7213 | R: 0.7573 | F1: 0.7389
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 134 | train_global_loss=0.0040
  [Entity]                   P: 0.8751 | R: 0.9147 | F1: 0.8944
  [Aspect#Category]          P: 0.8304 | R: 0.8685 | F1: 0.8491
  [Aspect#Category#Polarity] P: 0.7225 | R: 0.7557 | F1: 0.7387
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 135 | train_global_loss=0.0039
  [Entity]                   P: 0.8730 | R: 0.9160 | F1: 0.8940
  [Aspect#Category]          P: 0.8295 | R: 0.8690 | F1: 0.8488
  [Aspect#Category#Polarity] P: 0.7214 | R: 0.7557 | F1: 0.7381
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 136 | train_global_loss=0.0037
  [Entity]                   P: 0.8727 | R: 0.9173 | F1: 0.8944
  [Aspect#Category]          P: 0.8282 | R: 0.8710 | F1: 0.8491
  [Aspect#Category#Polarity] P: 0.7193 | R: 0.7565 | F1: 0.7375
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 137 | train_global_loss=0.0037
  [Entity]                   P: 0.8717 | R: 0.9180 | F1: 0.8942
  [Aspect#Category]          P: 0.8263 | R: 0.8710 | F1: 0.8481
  [Aspect#Category#Polarity] P: 0.7188 | R: 0.7578 | F1: 0.7378
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 138 | train_global_loss=0.0037
  [Entity]                   P: 0.8717 | R: 0.9180 | F1: 0.8942
  [Aspect#Category]          P: 0.8271 | R: 0.8718 | F1: 0.8489
  [Aspect#Category#Polarity] P: 0.7188 | R: 0.7578 | F1: 0.7378
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 139 | train_global_loss=0.0034
  [Entity]                   P: 0.8717 | R: 0.9180 | F1: 0.8942
  [Aspect#Category]          P: 0.8278 | R: 0.8723 | F1: 0.8494
  [Aspect#Category#Polarity] P: 0.7199 | R: 0.7586 | F1: 0.7387
--------------------------------------------------------------------------------

train:   0%|          | 0/186 [00:00<?, ?it/s]

eval:   0%|          | 0/16 [00:00<?, ?it/s]

Epoch 140 | train_global_loss=0.0040
  [Entity]                   P: 0.8727 | R: 0.9173 | F1: 0.8944
  [Aspect#Category]          P: 0.8275 | R: 0.8706 | F1: 0.8485
  [Aspect#Category#Polarity] P: 0.7202 | R: 0.7578 | F1: 0.7385
--------------------------------------------------------------------------------
Best epoch: 108
Best test Aspect Micro-F1: 0.851859

In [14]:
best_model = HierarchicalABSA(
    model_name=MODEL_NAME,
    n_entity=len(aspect2id),
    n_aspect=len(aspect_category2id),
    n_sentiment=len(SENTIMENT_SPACE),
).to(device)

best_model.load_state_dict(torch.load(OUTPUT_DIR / "best_checkpoint" / "model.pt", map_location=device))
best_model.eval()

test_metrics = run_epoch(best_model, test_loader, train_mode=False)
print(json.dumps(test_metrics, ensure_ascii=False, indent=2))

with open(OUTPUT_DIR / "test_metrics.json", "w", encoding="utf-8") as f:
    json.dump(test_metrics, f, ensure_ascii=False, indent=2)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: vinai/phobert-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |
lm_head.decoder.bias            | UNEXPECTED |  |
lm_head.dense.bias              | UNEXPECTED |  |
lm_head.dense.weight            | UNEXPECTED |  |
lm_head.layer_norm.bias         | UNEXPECTED |  |
lm_head.bias                    | UNEXPECTED |  |
lm_head.layer_norm.weight       | UNEXPECTED |  |
lm_head.decoder.weight          | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
/tmp/ipykernel_58/1399836253.py:7: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=torch.cuda.is_available() and train_mode)

eval:   0%|          | 0/16 [00:00<?, ?it/s]

/tmp/ipykernel_58/1399836253.py:23: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=torch.cuda.is_available() and train_mode):

{
  "loss": {
    "entity": 0.7828640695661306,
    "aspect": 0.8895616419613361,
    "polarity": 0.8999302797019482,
    "global": 5.1343434154987335
  },
  "entity": {
    "precision": 0.873913043477718,
    "recall": 0.9232283464560871,
    "micro_f1": 0.8978940645923369
  },
  "aspect": {
    "precision": 0.829029733958987,
    "recall": 0.8759818106652022,
    "micro_f1": 0.8518592959824487
  },
  "aspect_category": {
    "precision": 0.829029733958987,
    "recall": 0.8759818106652022,
    "micro_f1": 0.8518592959824487,
    "correct": 2119,
    "predicted": 2556,
    "gold": 2419
  },
  "aspect_category_polarity": {
    "precision": 0.7183098591546485,
    "recall": 0.7589913187264329,
    "micro_f1": 0.738090451761389,
    "correct": 1836,
    "predicted": 2556,
    "gold": 2419
  }
}

In [15]:
def run_epoch_for_debug_current_error(model, loader, tokenizer):
    model.eval()

    ent_true_all, ent_pred_all, ent_probs_all = [], [], []
    asp_true_all, asp_pred_all, asp_probs_all = [], [], []
    pol_logits_all, pol_true_all = [], []
    input_ids_all = []

    pbar = tqdm(loader, desc="test", leave=False)
    for batch in pbar:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        y_entity = batch["y_entity"].to(device)
        y_aspect = batch["y_aspect"].to(device)
        y_polarity = batch["y_polarity"].to(device)

        with torch.set_grad_enabled(False):
            with torch.cuda.amp.autocast(False):
                outputs = model(input_ids=input_ids, attention_mask=attention_mask)


        ent_probs = outputs["entity_probs"].detach().cpu()
        ent_pred = (ent_probs >= THRESHOLD_ENTITY).long()
        
        asp_probs = outputs["aspect_probs"].detach().cpu()
        asp_pred = (asp_probs >= THRESHOLD_ASPECT).long()
        
        ent_true = y_entity.long().detach().cpu()
        asp_true = y_aspect.long().detach().cpu()

        ent_true_all.append(ent_true)
        ent_pred_all.append(ent_pred)
        ent_probs_all.append(ent_probs)
        
        asp_true_all.append(asp_true)
        asp_pred_all.append(asp_pred)
        asp_probs_all.append(asp_probs)
        
        pol_logits_all.append(outputs["polarity_logits"].detach().cpu())
        pol_true_all.append(y_polarity.detach().cpu())

        input_ids_all.append(input_ids.detach().cpu())


    ent_true_cat = torch.cat(ent_true_all, dim=0)
    ent_pred_cat = torch.cat(ent_pred_all, dim=0)
    ent_probs_cat = torch.cat(ent_probs_all, dim=0)
    
    asp_true_cat = torch.cat(asp_true_all, dim=0)
    asp_pred_cat = torch.cat(asp_pred_all, dim=0)
    asp_probs_cat = torch.cat(asp_probs_all, dim=0)
    
    pol_logits_cat = torch.cat(pol_logits_all, dim=0)
    pol_true_cat = torch.cat(pol_true_all, dim=0)

    input_ids_cat = torch.cat(input_ids_all, dim=0)

    ent_p, ent_r, ent_f1 = micro_f1_from_binary(ent_true_cat, ent_pred_cat)
    asp_p, asp_r, asp_f1 = micro_f1_from_binary(asp_true_cat, asp_pred_cat)
    java_style = aspect_category_java_style_metrics(
        y_aspect=asp_true_cat,
        y_polarity=pol_true_cat,
        aspect_probs=asp_probs_cat,
        polarity_logits=pol_logits_cat,
        threshold_aspect=THRESHOLD_ASPECT,
    )

    pol_pred_cat = torch.argmax(pol_logits_cat, dim=-1)

    print("\n" + "="*50)
    print("BẮT ĐẦU IN CÁC TRƯỜNG HỢP PREDICT SAI LỆCH")
    print("="*50)
    
    for i in range(len(asp_true_cat)):
        # Sai Aspect (False Positive hoặc False Negative)
        aspect_mismatch = (asp_pred_cat[i] != asp_true_cat[i])
        
        # Sai Polarity (Dự đoán đúng Aspect nhưng sai cực tính)
        polarity_mismatch = (asp_pred_cat[i] == 1) & (asp_true_cat[i] == 1) & (pol_pred_cat[i] != pol_true_cat[i])

        if aspect_mismatch.any() or polarity_mismatch.any():
            print(aspect2id)
            print(aspect_category2id)
            print(sentiment2id)
            print(f"\n[Sample Index: {i}]")
            decoded_text = tokenizer.decode(input_ids_cat[i], skip_special_tokens=True)
            
            print(f"\n[Sample Index: {i}]")
            print(f"Text Review: {decoded_text}")
            print(f"1. Entity Probs/Logits: \n{ent_probs_cat[i].numpy()}")
            print(f"2. Aspect Category:")
            print(f"   - Probs  : {asp_probs_cat[i].numpy()}")
            print(f"   - Predict: {asp_pred_cat[i].numpy()}")
            print(f"   - Truth  : {asp_true_cat[i].numpy()}")
            print(f"3. Aspect Category Polarity:")
            print(f"   - Logits : \n{pol_logits_cat[i].numpy()}")
            print(f"   - Predict: {pol_pred_cat[i].numpy()}")
            print(f"   - Truth  : {pol_true_cat[i].numpy()}")
    print("\n" + "="*50 + "\n")
    # -----------------------------------------------
    metrics = {
        "entity": {"precision": ent_p, "recall": ent_r, "micro_f1": ent_f1},
        "aspect": {"precision": asp_p, "recall": asp_r, "micro_f1": asp_f1},
        "aspect_category": java_style["aspect_category"],
        "aspect_category_polarity": java_style["aspect_category_polarity"],
    }
    return metrics

In [16]:
best_model = HierarchicalABSA(
    model_name=MODEL_NAME,
    n_entity=len(aspect2id),
    n_aspect=len(aspect_category2id),
    n_sentiment=len(SENTIMENT_SPACE),
).to(device)

best_model.load_state_dict(torch.load(OUTPUT_DIR / "best_checkpoint" / "model.pt", map_location=device))
best_model.eval()

test_metrics = run_epoch_for_debug_current_error(best_model, test_loader, tokenizer)
print(json.dumps(test_metrics, ensure_ascii=False, indent=2))

with open(OUTPUT_DIR / "test_metrics.json", "w", encoding="utf-8") as f:
    json.dump(test_metrics, f, ensure_ascii=False, indent=2)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: vinai/phobert-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |
lm_head.decoder.bias            | UNEXPECTED |  |
lm_head.dense.bias              | UNEXPECTED |  |
lm_head.dense.weight            | UNEXPECTED |  |
lm_head.layer_norm.bias         | UNEXPECTED |  |
lm_head.bias                    | UNEXPECTED |  |
lm_head.layer_norm.weight       | UNEXPECTED |  |
lm_head.decoder.weight          | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

test:   0%|          | 0/16 [00:00<?, ?it/s]

/tmp/ipykernel_58/460096179.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(False):

==================================================
BẮT ĐẦU IN CÁC TRƯỜNG HỢP PREDICT SAI LỆCH
==================================================
{'AMBIENCE': 0, 'DRINKS': 1, 'FOOD': 2, 'LOCATION': 3, 'RESTAURANT': 4, 'SERVICE': 5}
{'AMBIENCE#GENERAL': 0, 'DRINKS#PRICES': 1, 'DRINKS#QUALITY': 2, 'DRINKS#STYLE&OPTIONS': 3, 'FOOD#PRICES': 4, 'FOOD#QUALITY': 5, 'FOOD#STYLE&OPTIONS': 6, 'LOCATION#GENERAL': 7, 'RESTAURANT#GENERAL': 8, 'RESTAURANT#MISCELLANEOUS': 9, 'RESTAURANT#PRICES': 10, 'SERVICE#GENERAL': 11}
{'negative': 0, 'neutral': 1, 'positive': 2}

[Sample Index: 0]

[Sample Index: 0]
Text Review: Đây là 1 trong những quán mà mình thích vì vị trà đậm và thơm cũng như mùi_vị đặc_trưng hơn hẳn những quán khác nè Trà sữa trân_châu sợi - 46k Trà sữa pha khá ngon , vị trà chát và mùi hương khá rõ , không quá ngọt , rất đúng với gu mình Trà đào - 45k Vị trà đào ở đây cũng đặc_biệt hơn hẳn những quán khác , không phải chua_ngọt như_thường thấy mà có mùi trà rất ngon Cà_phê đá xay - 65k Món đá xay ở đây uống cũng ngon không kém trà_nè , mùi_vị thơm hương cà_phê , vị đắng kết_hợp hoàn_hảo với độ béo ngọt của whipping cream , không quá đắng , cũng không quá ngọt hay lạt_lẽo mà dịu nhẹ , thơm và dễ uống lắm Trà vải thiết quan âm - 45k Trà vải có mùi_vị rất thơm ngon mùi vải mà vẫn nghe rõ vị trà , có chút vị chát nhẹ mùi trà thơm rất thích , không phải chỉ toàn vị syrup vải ngọt gắt như nhiều chỗ khác Do trà ở đây pha khá đậm nên bạn nào uống mà đang đói sẽ dễ say nha , hoặc ban_đêm có_thể khó ngủ à , cảnh_báo trước Trà thiết quan âm latte - 47k Ly này thì vị trà rất đậm nên cảm_giác hơi nhạt và chát , phần kem sữa bên trên béo béo uống chung thì vừa
1. Entity Probs/Logits:
[2.4042664e-04 1.0000000e+00 1.4505050e-02 2.2768156e-04 4.8532408e-02
 2.8371803e-02]
2. Aspect Category:
   - Probs  : [2.1597475e-04 9.9305856e-01 1.0000000e+00 9.9999332e-01 9.2043795e-02
 1.0120275e-02 3.2037285e-01 1.1206310e-04 7.3911446e-01 1.2075277e-04
 1.0036598e-03 7.5920471e-03]
   - Predict: [0 1 1 1 0 0 0 0 1 0 0 0]
   - Truth  : [0 1 1 1 0 0 0 0 1 0 0 0]
3. Aspect Category Polarity:
   - Logits :
[[ 2.2456822  -2.0156906   0.1639886 ]
 [-2.3286424   7.537644   -5.558579  ]
 [-1.7859536   0.5714426   0.341017  ]
 [ 0.11358838 -3.1680622   2.6383855 ]
 [-1.4421053   6.2974987  -4.8591776 ]
 [-3.4867995   0.27487797  3.39048   ]
 [-3.4347126  -0.26208237  2.6399415 ]
 [ 0.06432983  1.2517328  -0.52953494]
 [-0.06116977  0.32598922 -0.9149915 ]
 [ 2.5838113   3.2954133  -4.6591325 ]
 [-1.9189222   4.42583    -2.5762    ]
 [ 0.01459002 -1.7700826   2.5201278 ]]
   - Predict: [0 1 1 2 1 2 2 1 1 1 1 2]
   - Truth  : [-100    1    2    1 -100 -100 -100 -100    2 -100 -100 -100]
{'AMBIENCE': 0, 'DRINKS': 1, 'FOOD': 2, 'LOCATION': 3, 'RESTAURANT': 4, 'SERVICE': 5}
{'AMBIENCE#GENERAL': 0, 'DRINKS#PRICES': 1, 'DRINKS#QUALITY': 2, 'DRINKS#STYLE&OPTIONS': 3, 'FOOD#PRICES': 4, 'FOOD#QUALITY': 5, 'FOOD#STYLE&OPTIONS': 6, 'LOCATION#GENERAL': 7, 'RESTAURANT#GENERAL': 8, 'RESTAURANT#MISCELLANEOUS': 9, 'RESTAURANT#PRICES': 10, 'SERVICE#GENERAL': 11}
{'negative': 0, 'neutral': 1, 'positive': 2}

[Sample Index: 1]

[Sample Index: 1]
Text Review: Bữa lướt facebook nhỏ bạn thấy có check-in ly trà sữa khổng_lồ cùng viên phô_mai to ú nụ . Mình bị hấp_dẫn trong ngày từ cái nhìn đầu_tiên nên đòi anh người_yêu chở đi mua cho bằng được hihi . TRÀ SỮA 1ST TEA đ / c : 60D Nguyễn_Thông , Q3 ( ngay ngã 3 Kỳ_Đồng và Nguyễn_Thông ) Mở_cửa : 8h - 22h Facebook : 1ST TEA Đây là ly size khổng_lồ của quán . Dung_tích theo mình nghĩ cỡ 1 lít chứ chẳng chơi . Hai đứa muốn ngập mặt tại_chỗ . Mình nói là ngon lắm nhưng không nghe . Tới khi ly trà sữa xuất_hiện cùng 2 viên phô_mai to ú nụ thì tranh_giành check-in đầu_tiên cho bằng được Như mọi người thấy viên phô_mai của quán to hơn bất_kỳ quán nào khác . 1 viên theo mình nhớ giá chỉ có 9k thôi . Với ly khổng_lồ thì có mặc_định sẵn có trân_châu , muốn ăn thêm thạch khác có_thể order thêm . Mình tán mụ_thị_viên phô_mai cho mọi người thấy độ ú nụ dễ_thương của em ấy . Việc múc bằng muỗng để múc phô_mai khó lắm nha , to và nặng quá mà . Phô_mai quán làm thơm vị sữa_tươi và chút vị béo nhẹ . Ăn hoài không ngán . Ăn ngon tụi mình còn mua mỗi đứa thêm 1 viên nữa hihi . Noel
1. Entity Probs/Logits:
[5.7489299e-03 9.9998832e-01 9.9829596e-01 9.9999964e-01 9.9999821e-01
 4.9756531e-04]
2. Aspect Category:
   - Probs  : [8.65107635e-04 8.11689347e-02 1.61272720e-01 9.92597818e-01
 4.84202914e-02 9.99660492e-01 9.56657588e-01 9.99999762e-01
 7.43394315e-01 9.99990582e-01 3.09139444e-03 1.17788164e-04]
   - Predict: [0 0 0 1 0 1 1 1 1 1 0 0]
   - Truth  : [0 0 1 1 1 1 1 1 0 1 0 0]
3. Aspect Category Polarity:
   - Logits :
[[-3.9348485  -1.0010973   4.384567  ]
 [-1.8011463  -5.9291964   6.416226  ]
 [-5.078615   -4.1533732   7.3571754 ]
 [-5.8236556  -5.5782948   8.994265  ]
 [-3.668483    0.31620833  1.7806902 ]
 [-5.608924   -5.7145076   9.012233  ]
 [-6.6303134  -5.827508   11.517837  ]
 [-6.900928    5.1880655   0.73600394]
 [-7.2173038  -4.1108165   9.050877  ]
 [-3.3585851   6.3393784  -2.0626006 ]
 [-3.1175146  -5.1368046   6.7147985 ]
 [-3.5527103  -1.6331772   5.2514477 ]]
   - Predict: [2 2 2 2 2 2 2 1 2 1 2 2]
   - Truth  : [-100 -100    2    2    2    2    2    1 -100    1 -100 -100]
{'AMBIENCE': 0, 'DRINKS': 1, 'FOOD': 2, 'LOCATION': 3, 'RESTAURANT': 4, 'SERVICE': 5}
{'AMBIENCE#GENERAL': 0, 'DRINKS#PRICES': 1, 'DRINKS#QUALITY': 2, 'DRINKS#STYLE&OPTIONS': 3, 'FOOD#PRICES': 4, 'FOOD#QUALITY': 5, 'FOOD#STYLE&OPTIONS': 6, 'LOCATION#GENERAL': 7, 'RESTAURANT#GENERAL': 8, 'RESTAURANT#MISCELLANEOUS': 9, 'RESTAURANT#PRICES': 10, 'SERVICE#GENERAL': 11}
{'negative': 0, 'neutral': 1, 'positive': 2}

[Sample Index: 2]

[Sample Index: 2]
Text Review: Nghe phông phanh về trà sữa có viên phô_mai to ú ù lâu rồi mà chưa có dịp đi thử . Thế_là hôm_qua cũng rảnh_rỗi nên rủ tụi ‘ cạ cứng ’ đi uống thử . Đoán là viên phô_mai chắc cũng to to , ai dè to thật , ăn một phát mà muốn ghiền luôn ! 1st Tea trang_trí chủ_đạo là 3 tông màu trắng-xanh-vàng rất dễ_thương Hình_vẽ hoạt_hình vui_nhộn … và dành hẳn cho bạn một góc chụp hình check-in Menu quán khá đa_dạng , phong_phú , có các loại nước như : trà , trà_sữa , macchiato , đá xay , … mà giá thì chỉ dao_động từ 21K – 44K thôi . Tuỳ size , tuỳ loại nước uống mà bạn sẽ nhận được ly khác nhau , nhưng_mà size nào thì ly cũng to cả Trà sữa phô_mai ú ù – size M : 36K Mình thì mình ưng phô_mai nên mình oder một ly trà sữa trân_châu có viên phô_mai bự-chà-bá. Thạch trân chân hoàng_kim dai dai thơm thơm , trà sữa rất vừa uống . Matcha_Macchiato – size M : 34K Việt quất phô_mai đá xay – size S : 37K Nói là size S vậy thôi chứ ‘ quất ’ 1 ly thôi là no-cành-hông rồi đó . Nhóm tụi mình uống 4 ly mà chỉ
1. Entity Probs/Logits:
[6.4550406e-01 1.0000000e+00 5.9363753e-01 9.7321390e-05 7.9614796e-02
 1.0779112e-03]
2. Aspect Category:
   - Probs  : [8.5962003e-01 9.4984096e-01 9.9980861e-01 1.0000000e+00 2.8221855e-01
 3.9838389e-01 8.2151192e-01 3.5931302e-05 1.0512028e-04 2.2934022e-05
 6.3924009e-01 4.1450732e-04]
   - Predict: [1 1 1 1 0 0 1 0 0 0 1 0]
   - Truth  : [1 1 1 1 0 0 1 0 1 0 0 0]
3. Aspect Category Polarity:
   - Logits :
[[-2.161851   -0.5720581   2.8692815 ]
 [-5.990444    3.3648863   1.538367  ]
 [-6.455235   -0.4032255   4.915194  ]
 [-4.004849   -3.0051835   5.8864923 ]
 [-3.1516128  -0.3794715   3.1260617 ]
 [-4.270178   -3.3577352   6.9369717 ]
 [-5.339468   -1.4306679   5.4050584 ]
 [-1.0094984   1.9855909  -0.3409188 ]
 [-2.6887715  -2.535664    3.912738  ]
 [ 2.839939   -0.7144192  -1.9979143 ]
 [-4.756387    0.7098197   3.5892913 ]
 [-1.6759379  -0.70144314  2.6152835 ]]
   - Predict: [2 1 2 2 2 2 2 1 2 0 2 2]
   - Truth  : [   2    2    2    2 -100 -100    2 -100    2 -100 -100 -100]
{'AMBIENCE': 0, 'DRINKS': 1, 'FOOD': 2, 'LOCATION': 3, 'RESTAURANT': 4, 'SERVICE': 5}
{'AMBIENCE#GENERAL': 0, 'DRINKS#PRICES': 1, 'DRINKS#QUALITY': 2, 'DRINKS#STYLE&OPTIONS': 3, 'FOOD#PRICES': 4, 'FOOD#QUALITY': 5, 'FOOD#STYLE&OPTIONS': 6, 'LOCATION#GENERAL': 7, 'RESTAURANT#GENERAL': 8, 'RESTAURANT#MISCELLANEOUS': 9, 'RESTAURANT#PRICES': 10, 'SERVICE#GENERAL': 11}
{'negative': 0, 'neutral': 1, 'positive': 2}

[Sample Index: 3]

[Sample Index: 3]
Text Review: Lại là mình tín_đồ nghiện trà sữa đây , thấy quán trà sữa này có bán viên phô_mai to ú nù nghe hấp_dẫn quá_chừng nên đi uống liền . Quán nằm ngay trung_tâm giá cũng mềm , trang_trí dễ_thương , nhân_viên nhiệt_tình Menu quán đơn_giản chỉ vài món giá cũng rẻ so với mặt_bằng trung_tâm Ly trà sữa 20k thêm phômai ú nù 15k Phô_mai ú nù siêu bự thật_ra như cục pudding hơn Mùi béo thơm nhưng ko nghe mùi phômai đậm mà nghe mùi vani trứng , cũng ngon chứ ko dở Trân_châu hoàng_kim 5k mềm thơm , vị trà sữa uống cũng được ko quá ngọt bình_thường như những quán khác , nước nhiều đá ít nha Trà đen macchiato 25k trà đậm ít đường ko ngọt lắm Milkfoam bên trên ngon nè xài kem whipping đánh ra luôn nha , ngọt béo chứ ko phải mặn mình khá thích Quán decor đơn_giản tông vàng ấm_áp Chúc các bạn ăn ngon_miệng .
1. Entity Probs/Logits:
[0.9996902  1.         0.99719536 0.994396   0.99191475 0.99987376]
2. Aspect Category:
   - Probs  : [9.9995267e-01 4.8549590e-01 9.9998641e-01 9.9994862e-01 9.9299639e-01
 9.9898273e-01 9.9982256e-01 9.9903238e-01 2.1907674e-02 4.5764452e-04
 9.9666154e-01 9.9997592e-01]
   - Predict: [1 0 1 1 1 1 1 1 0 0 1 1]
   - Truth  : [1 0 1 1 0 1 1 1 0 0 1 1]
3. Aspect Category Polarity:
   - Logits :
[[-3.9600015   0.07112718  3.9203415 ]
 [-6.560132    2.0307899   3.6080854 ]
 [-4.779801   -1.1077707   3.9960423 ]
 [-2.2324317  -1.623901    2.5941918 ]
 [-4.399595   -2.1200411   5.5665245 ]
 [-4.7316914  -2.0915227   6.069832  ]
 [-5.531341   -1.2490338   5.7286    ]
 [-3.7710488  -3.0478773   6.834675  ]
 [-4.430594   -0.5112842   4.1572094 ]
 [ 1.0968139  -0.45859125 -1.169442  ]
 [-5.477829   -1.3257229   5.6386857 ]
 [-5.640664   -2.9145813   8.00625   ]]
   - Predict: [2 2 2 2 2 2 2 2 2 0 2 2]
   - Truth  : [   2 -100    2    1 -100    2    2    2 -100 -100    2    2]
{'AMBIENCE': 0, 'DRINKS': 1, 'FOOD': 2, 'LOCATION': 3, 'RESTAURANT': 4, 'SERVICE': 5}
{'AMBIENCE#GENERAL': 0, 'DRINKS#PRICES': 1, 'DRINKS#QUALITY': 2, 'DRINKS#STYLE&OPTIONS': 3, 'FOOD#PRICES': 4, 'FOOD#QUALITY': 5, 'FOOD#STYLE&OPTIONS': 6, 'LOCATION#GENERAL': 7, 'RESTAURANT#GENERAL': 8, 'RESTAURANT#MISCELLANEOUS': 9, 'RESTAURANT#PRICES': 10, 'SERVICE#GENERAL': 11}
{'negative': 0, 'neutral': 1, 'positive': 2}

[Sample Index: 4]

[Sample Index: 4]
Text Review: Không_gian quán sang_trọng khá đẹp mang phong_cách Châu_Âu , giá_cả lại khá rẻ và món ăn cũng rất ngon , các món ăn được trang_trí nhìn rất hấp_dẫn , nhân_viên phục_vụ rất tốt .
1. Entity Probs/Logits:
[9.9999833e-01 6.3969887e-06 9.9999952e-01 2.6338578e-06 5.0531612e-03
 9.9999976e-01]
2. Aspect Category:
   - Probs  : [9.9999881e-01 1.1932136e-07 4.9164004e-08 8.2989999e-07 7.4828476e-01
 9.9999976e-01 9.9942881e-01 2.0470034e-06 1.7476010e-09 1.1637213e-07
 3.0702051e-02 9.9999976e-01]
   - Predict: [1 0 0 0 1 1 1 0 0 0 0 1]
   - Truth  : [1 0 0 0 0 1 1 0 0 0 1 1]
3. Aspect Category Polarity:
   - Logits :
[[ -5.179377   -6.686334   10.885206 ]
 [ -4.051954   -2.9397666   6.324214 ]
 [ -2.8818986  -4.142845    5.2941265]
 [ -5.1282716  -1.7351162   4.6375523]
 [ -3.2315252  -8.458591   10.406229 ]
 [ -5.5750256  -6.292016    8.57221  ]
 [ -5.1692805  -7.157992   11.66755  ]
 [ -2.729356    3.403864   -1.3752666]
 [ -6.988177   -3.7552383   7.455984 ]
 [ -1.7101862 -10.458347    9.467762 ]
 [ -4.142857   -4.3108816   6.7055883]
 [ -6.579922   -4.884047   10.026944 ]]
   - Predict: [2 2 2 2 2 2 2 1 2 2 2 2]
   - Truth  : [   2 -100 -100 -100 -100    2    2 -100 -100 -100    2    2]
{'AMBIENCE': 0, 'DRINKS': 1, 'FOOD': 2, 'LOCATION': 3, 'RESTAURANT': 4, 'SERVICE': 5}
{'AMBIENCE#GENERAL': 0, 'DRINKS#PRICES': 1, 'DRINKS#QUALITY': 2, 'DRINKS#STYLE&OPTIONS': 3, 'FOOD#PRICES': 4, 'FOOD#QUALITY': 5, 'FOOD#STYLE&OPTIONS': 6, 'LOCATION#GENERAL': 7, 'RESTAURANT#GENERAL': 8, 'RESTAURANT#MISCELLANEOUS': 9, 'RESTAURANT#PRICES': 10, 'SERVICE#GENERAL': 11}
{'negative': 0, 'neutral': 1, 'positive': 2}

[Sample Index: 6]

[Sample Index: 6]
Text Review: Menu của nhà_hàng cực đa_dạng mà hầu_như món nào cũng trang_bị rất đẹp , hương_vị nhẹ_nhàng nhưng vẫn vừa_miệng , không_gian đẹp sang_trọng rất phù_hợp để hẹn_hò , nhân_viên phục_vụ tốt . Tuy_nhiên giá_cả cũng có hơi cao 1 tý .
1. Entity Probs/Logits:
[9.999565e-01 8.561060e-05 9.999945e-01 6.531728e-05 9.999994e-01
 9.999988e-01]
2. Aspect Category:
   - Probs  : [9.9998617e-01 3.8143736e-07 1.1613304e-06 5.8209966e-06 9.9597436e-01
 9.9995971e-01 9.9972135e-01 1.6798940e-05 9.9876583e-01 3.8370963e-06
 9.7966659e-01 9.9999917e-01]
   - Predict: [1 0 0 0 1 1 1 0 1 0 1 1]
   - Truth  : [1 0 0 0 0 1 1 0 0 0 1 1]
3. Aspect Category Polarity:
   - Logits :
[[ -4.4014745   -7.125499    11.008396  ]
 [  4.667201    -3.3822799   -1.1993805 ]
 [ -0.5914577   -3.6479762    2.6433177 ]
 [ -1.8610967   -4.463058     3.6151445 ]
 [  9.482205     2.145398   -11.87383   ]
 [ -8.971506    -2.979951     8.32417   ]
 [ -1.8468068   -7.091715    10.010298  ]
 [ -1.8961184    2.1912427   -0.58136886]
 [ -3.6291804   -7.573809     8.698389  ]
 [ -0.17204763  -8.699031     6.780357  ]
 [  6.838535    -1.6501192   -5.1889358 ]
 [ -3.3702123   -6.206338     8.943864  ]]
   - Predict: [2 0 2 2 0 2 2 1 2 2 0 2]
   - Truth  : [   2 -100 -100 -100 -100    2    2 -100 -100 -100    0    2]
{'AMBIENCE': 0, 'DRINKS': 1, 'FOOD': 2, 'LOCATION': 3, 'RESTAURANT': 4, 'SERVICE': 5}
{'AMBIENCE#GENERAL': 0, 'DRINKS#PRICES': 1, 'DRINKS#QUALITY': 2, 'DRINKS#STYLE&OPTIONS': 3, 'FOOD#PRICES': 4, 'FOOD#QUALITY': 5, 'FOOD#STYLE&OPTIONS': 6, 'LOCATION#GENERAL': 7, 'RESTAURANT#GENERAL': 8, 'RESTAURANT#MISCELLANEOUS': 9, 'RESTAURANT#PRICES': 10, 'SERVICE#GENERAL': 11}
{'negative': 0, 'neutral': 1, 'positive': 2}

[Sample Index: 7]

[Sample Index: 7]
Text Review: Quán khá độc_đáo với thiết_kế nhìn rất cao_cấp , trang_trí theo phong_cách châu_âu , hương_vị các món ăn ngon mà giá_cả lại cực_kỳ hợp_lý nữa . Nhân_viên cũng rất thân_thiện và nhiệt_tình .
1. Entity Probs/Logits:
[9.9999976e-01 1.2276941e-05 9.9999928e-01 1.6241360e-06 5.0175242e-04
 9.9999964e-01]
2. Aspect Category:
   - Probs  : [9.9999976e-01 5.5670387e-07 6.5664594e-08 5.3228820e-07 9.9991906e-01
 9.9999964e-01 6.5836525e-01 1.3439944e-06 2.5352492e-08 2.0821307e-07
 3.3560031e-05 9.9999964e-01]
   - Predict: [1 0 0 0 1 1 1 0 0 0 0 1]
   - Truth  : [1 0 0 0 0 1 0 0 0 0 1 1]
3. Aspect Category Polarity:
   - Logits :
[[ -6.0952964   -5.498844    10.490459  ]
 [ -3.9131448   -1.6499336    5.2688413 ]
 [ -3.7807457   -1.9038223    4.1357203 ]
 [ -4.642983    -1.4082987    4.030217  ]
 [ -3.230119    -8.716702    10.931706  ]
 [ -5.9657593   -6.6805844    9.659539  ]
 [ -3.6884885   -7.9728518   10.997208  ]
 [ -3.0307155    2.7858772   -0.36058316]
 [ -6.14617     -3.908008     6.8020306 ]
 [ -1.4764326  -10.137986     8.886774  ]
 [ -3.7473845   -3.9239738    6.0107694 ]
 [ -6.9232507   -5.3941493   10.901268  ]]
   - Predict: [2 2 2 2 2 2 2 1 2 2 2 2]
   - Truth  : [   2 -100 -100 -100 -100    2 -100 -100 -100 -100    2    2]
{'AMBIENCE': 0, 'DRINKS': 1, 'FOOD': 2, 'LOCATION': 3, 'RESTAURANT': 4, 'SERVICE': 5}
{'AMBIENCE#GENERAL': 0, 'DRINKS#PRICES': 1, 'DRINKS#QUALITY': 2, 'DRINKS#STYLE&OPTIONS': 3, 'FOOD#PRICES': 4, 'FOOD#QUALITY': 5, 'FOOD#STYLE&OPTIONS': 6, 'LOCATION#GENERAL': 7, 'RESTAURANT#GENERAL': 8, 'RESTAURANT#MISCELLANEOUS': 9, 'RESTAURANT#PRICES': 10, 'SERVICE#GENERAL': 11}
{'negative': 0, 'neutral': 1, 'positive': 2}

[Sample Index: 8]

[Sample Index: 8]
Text Review: Tối nay bọn mình vừa ghé quán ăn . Đây là lần thứ hai , chất_lượng ngon vẫn không đổi . Quán ở vỉa_hè đường Phạm_Văn_Đồng rất thoáng mát . Mình gọi 2 tô mì hoành_thánh xương 28 k / tô . Mì hoành_thánh không xương thì 22 k / tô . Nước_lèo rất ngon , mình ăn 2 lần nhưng không bị dị_ứng vì bột_ngọt nhiều . Đặc_biệt mình rất thích mì và hoành thành ở đây . Mì được chú tự làm , rất dai , mềm và có độ beo_béo mình rất thích . Hoành_thánh chất_lượng , ăn mình thấy có cả tôm nhỏ bên trong , vị vừa ăn , nhân nhiều , bột hoành_thánh không bị bở , không bị sượng . Chú bán cũng dễ_thương lắm , chú mới bán 2 tháng thôi , mà mở đúng tháng mưa nên không bán đắc lắm nên mình viết bài review mấy bạn đến ủng_hộ chú nha giá hợp_lý mà chất_lượng lắm ý Quán nè , đầu đường 27 , vừa chạy qua đường 25 , qua cầu bộ_hành nhìn bên phải là thấy ngay Tô nay mình chụp lúc ăn mấy đũa rồi , lúc ăn ngon quá quên mất chụp hình lúc đầu Ăn tô này là no bụng ngay ý Mì nè , rất dai và ngon , beo_béo nữa , ăn thích lắm Mình chộp được mì ở trong xe của chú , nhìn hoành_tráng g@@
1. Entity Probs/Logits:
[9.9999952e-01 1.8980003e-05 9.9999797e-01 9.9999964e-01 9.9952817e-01
 9.9999273e-01]
2. Aspect Category:
   - Probs  : [9.9999964e-01 3.7359979e-07 1.9375859e-07 9.8162002e-07 9.9997771e-01
 9.9999976e-01 9.9980348e-01 9.9999976e-01 9.6988130e-01 2.8815537e-05
 5.3942367e-03 9.9999762e-01]
   - Predict: [1 0 0 0 1 1 1 1 1 0 0 1]
   - Truth  : [1 0 0 0 1 1 1 1 1 0 0 1]
3. Aspect Category Polarity:
   - Logits :
[[-7.235883   -6.217014   12.169305  ]
 [-3.4949353  -1.0803626   4.503699  ]
 [-1.885408   -2.3047278   3.2446241 ]
 [-4.3829346  -3.7154415   6.1204934 ]
 [-6.3745685   0.03733736  4.4200916 ]
 [-6.7198496  -7.957718   10.9828005 ]
 [-8.192647   -4.6744456  12.19575   ]
 [-7.4773645   4.437706    1.8151239 ]
 [-8.897258   -5.654537   11.625117  ]
 [-4.7237735  -2.4631991   5.456465  ]
 [-4.201168   -3.7839017   5.657519  ]
 [-6.5681715  -5.990575   11.069077  ]]
   - Predict: [2 2 2 2 2 2 2 1 2 2 2 2]
   - Truth  : [   2 -100 -100 -100    2    2    2    2    2 -100 -100    2]
{'AMBIENCE': 0, 'DRINKS': 1, 'FOOD': 2, 'LOCATION': 3, 'RESTAURANT': 4, 'SERVICE': 5}
{'AMBIENCE#GENERAL': 0, 'DRINKS#PRICES': 1, 'DRINKS#QUALITY': 2, 'DRINKS#STYLE&OPTIONS': 3, 'FOOD#PRICES': 4, 'FOOD#QUALITY': 5, 'FOOD#STYLE&OPTIONS': 6, 'LOCATION#GENERAL': 7, 'RESTAURANT#GENERAL': 8, 'RESTAURANT#MISCELLANEOUS': 9, 'RESTAURANT#PRICES': 10, 'SERVICE#GENERAL': 11}
{'negative': 0, 'neutral': 1, 'positive': 2}

[Sample Index: 9]

[Sample Index: 9]
Text Review: Quán này nằm trong hẻm , hơi khó tìm , ở đây đa_số khách quen ghé ăn nhiều . Quán mở từ thứ hai đến thứ_bảy , 14h tới 18h3 0 . Đồ_ăn ở đây ngon , giá ok , nhưng quán có một_số qui_định , ban_đầu cũng làm mình bất_ngờ . Không_gian quán nhỏ , ngồi ngoài_trời thoáng mát . Ở đây đi trên 3 người thì chỉ được để 3 xe , còn lại phải gửi đầu hẻm , các bạn lưu_ý giùm . Thực_đơn đúng các món ăn vặt teen khoái_khẩu , vì quán gần trường_học nên đa_số khách là các bạn học_sinh . Cacao 1,5 k một hủ , trên 6 hủ mới bán Tuy chảnh vậy_mà chất_lượng cacao thì ngon khỏi nói , ăn mát mát , đi đông người thì nên gọi nhiều , vì một người ăn cỡ 3-4 hủ mới đủ đô Cacao đông đá ngọt thơm Bì cuốn 2 k / cuốn , trên 10 cuốn mới bán Cuốn ngon , nước châm vừa ăn Yaourt đá 10 k / ly , có nhiều loại như số dâu , sốt bạc_hà ... Theo mình thấy thì vị siro rất ít , chỉ nghe mỗi mùi yaourt thôi Này là ly xí muội , uống cũng ok Chúc các bạn ăn ngon_miệng
1. Entity Probs/Logits:
[0.9962798  0.9999999  0.99988496 0.99998665 0.99995005 0.13883674]
2. Aspect Category:
   - Probs  : [0.99957377 0.6460317  0.99678075 0.9943666  0.9999938  0.99999976
 0.99999    0.99999297 0.00434005 0.9917326  0.965775   0.02931515]
   - Predict: [1 1 1 1 1 1 1 1 0 1 1 0]
   - Truth  : [1 0 1 0 0 1 1 1 0 1 1 0]
3. Aspect Category Polarity:
   - Logits :
[[-6.895354    2.0967171   4.338676  ]
 [-5.747879    0.11511318  5.134     ]
 [-7.079511   -2.7046216   7.2988605 ]
 [-6.3095     -2.813697    7.5757627 ]
 [-4.873547    3.4079952   0.12155208]
 [-8.560726   -4.246174   10.134106  ]
 [-9.887423   -1.4229943   9.516336  ]
 [ 1.4985387   2.7266     -3.674148  ]
 [-6.244314   -1.7153181   5.8175726 ]
 [-3.4808261   3.1301022   0.6303904 ]
 [-4.4735937  -3.8138208   6.536794  ]
 [-5.4273334   0.44074416  4.6060824 ]]
   - Predict: [2 2 2 2 1 2 2 1 2 1 2 2]

In [17]:
def predict_texts(model, tokenizer, texts: List[str], threshold_entity=0.5, threshold_aspect=0.5):
    model.eval()
    outputs = []
    with torch.no_grad():
        for text in texts:
            enc = tokenizer(
                text,
                truncation=True,
                max_length=MAX_LENGTH,
                padding="max_length",
                return_tensors="pt",
            )
            input_ids = enc["input_ids"].to(device)
            attention_mask = enc["attention_mask"].to(device)
            out = model(input_ids=input_ids, attention_mask=attention_mask)

            entity_probs = out["entity_probs"][0].cpu()
            aspect_probs = out["aspect_probs"][0].cpu()
            polarity_logits = out["polarity_logits"][0].cpu()
            polarity_pred = polarity_logits.argmax(dim=-1)

            polarity_softmax = torch.softmax(polarity_logits, dim=-1)
            
            pred_entities = [
                id2aspect[i]
                for i, p in enumerate(entity_probs.tolist())
                if p >= threshold_entity
            ]
            pred_aspect_categories = [
                id2aspect_category[i]
                for i, p in enumerate(aspect_probs.tolist())
                if p >= threshold_aspect
            ]
            pred_triplets = []
            polarity_score = {}
            
            for ac in pred_aspect_categories:
                ac_idx = aspect_category2id[ac]
                pol = id2sentiment[int(polarity_pred[ac_idx].item())]
                pred_triplets.append((ac, pol))
                ac_scores = polarity_softmax[ac_idx].tolist()

                polarity_score[ac] = {
                    id2sentiment[i]: score 
                    for i, score in enumerate(ac_scores)}
            
            outputs.append({
                "text": text,
                "pred_entities": pred_entities,
                "pred_aspect_categories": pred_aspect_categories,
                "pred_aspect_category_sentiments": pred_triplets,
                "polarity_score": polarity_score,
            })
    return outputs

sample_texts = [
    "Đồ ăn ngon nhưng nhân_viên phục_vụ chậm",
    "Không_gian đẹp, giá hợp_lý và menu đa_dạng.",
    "Vị_trí khó tìm, món ăn bình_thường.",
]

sample_predictions = predict_texts(best_model, tokenizer, sample_texts)

In [18]:
sample_predictions

[{'text': 'Đồ ăn ngon nhưng nhân_viên phục_vụ chậm',
  'pred_entities': ['FOOD', 'SERVICE'],
  'pred_aspect_categories': ['FOOD#QUALITY', 'SERVICE#GENERAL'],
  'pred_aspect_category_sentiments': [('FOOD#QUALITY', 'positive'),
   ('SERVICE#GENERAL', 'negative')],
  'polarity_score': {'FOOD#QUALITY': {'negative': 1.4696984180773143e-06,
    'neutral': 4.4311246938377735e-07,
    'positive': 0.9999980926513672},
   'SERVICE#GENERAL': {'negative': 0.9981062412261963,
    'neutral': 0.001679011038504541,
    'positive': 0.00021471804939210415}}},
 {'text': 'Không_gian đẹp, giá hợp_lý và menu đa_dạng.',
  'pred_entities': ['AMBIENCE', 'FOOD', 'RESTAURANT'],
  'pred_aspect_categories': ['AMBIENCE#GENERAL',
   'FOOD#STYLE&OPTIONS',
   'RESTAURANT#PRICES'],
  'pred_aspect_category_sentiments': [('AMBIENCE#GENERAL', 'positive'),
   ('FOOD#STYLE&OPTIONS', 'positive'),
   ('RESTAURANT#PRICES', 'positive')],
  'polarity_score': {'AMBIENCE#GENERAL': {'negative': 1.435496187696117e-06,
    'neutral': 4.393204022790087e-08,
    'positive': 0.9999985694885254},
   'FOOD#STYLE&OPTIONS': {'negative': 3.214168827980757e-05,
    'neutral': 8.646858077554498e-06,
    'positive': 0.9999592304229736},
   'RESTAURANT#PRICES': {'negative': 2.796979742925032e-06,
    'neutral': 4.144843387621222e-06,
    'positive': 0.999993085861206}}},
 {'text': 'Vị_trí khó tìm, món ăn bình_thường.',
  'pred_entities': ['FOOD', 'LOCATION'],
  'pred_aspect_categories': ['FOOD#QUALITY', 'LOCATION#GENERAL'],
  'pred_aspect_category_sentiments': [('FOOD#QUALITY', 'positive'),
   ('LOCATION#GENERAL', 'negative')],
  'polarity_score': {'FOOD#QUALITY': {'negative': 0.00011028449080185965,
    'neutral': 2.37447748077102e-05,
    'positive': 0.9998660087585449},
   'LOCATION#GENERAL': {'negative': 0.9973824620246887,
    'neutral': 2.680299621715676e-05,
    'positive': 0.002590806456282735}}}]

In [19]:
import pandas as pd
import ast

# Giả sử em đã có biến sample_predictions từ hàm predict_texts

# ==========================================
# 1. LƯU SAMPLE_PREDICTIONS RA FILE CSV
# ==========================================
# Chuyển list of dicts thành pandas DataFrame
df = pd.DataFrame(sample_predictions)

# Lưu ra file csv (chú ý dùng encoding utf-8-sig để không bị lỗi font tiếng Việt)
df.to_csv("absa_predictions.csv", index=False, encoding="utf-8-sig")
print("Đã lưu dự đoán ra file absa_predictions.csv")


# ==========================================
# 2. ĐỌC LẠI TỪ FILE CSV
# ==========================================
df_read = pd.read_csv("absa_predictions.csv")

# Các cột chứa list/tuple đang bị hiểu là chuỗi (string)
# Ta cần dùng ast.literal_eval để chuyển chúng lại thành cấu trúc dữ liệu ban đầu
columns_to_parse = [
    "pred_entities", 
    "pred_aspect_categories", 
    "pred_aspect_category_sentiments"
]

for col in columns_to_parse:
    df_read[col] = df_read[col].apply(ast.literal_eval)

# Nếu em muốn đưa dữ liệu về lại dạng list of dictionaries y hệt ban đầu:
loaded_predictions = df_read.to_dict('records')

# In thử mẫu đầu tiên để kiểm tra kiểu dữ liệu
print(loaded_predictions[0])
print(type(loaded_predictions[0]["pred_aspect_category_sentiments"])) # Sẽ trả về <class 'list'>

Đã lưu dự đoán ra file absa_predictions.csv
{'text': 'Đồ ăn ngon nhưng nhân_viên phục_vụ chậm', 'pred_entities': ['FOOD', 'SERVICE'], 'pred_aspect_categories': ['FOOD#QUALITY', 'SERVICE#GENERAL'], 'pred_aspect_category_sentiments': [('FOOD#QUALITY', 'positive'), ('SERVICE#GENERAL', 'negative')], 'polarity_score': "{'FOOD#QUALITY': {'negative': 1.4696984180773143e-06, 'neutral': 4.4311246938377735e-07, 'positive': 0.9999980926513672}, 'SERVICE#GENERAL': {'negative': 0.9981062412261963, 'neutral': 0.001679011038504541, 'positive': 0.00021471804939210415}}"}
<class 'list'>

In [21]:
def to_english_label(pairs: List[Tuple[str, str]]) -> str:
    if not pairs:
        return ""
    uniq = list(OrderedDict.fromkeys((ac, normalize_sentiment(pol)) for ac, pol in pairs))
    return ", ".join([f"{{{ac}, {pol}}}" for ac, pol in uniq])

def save_split_predictions(records: List[Dict], split_name: str) -> pd.DataFrame:
    texts = [r["ws_review"] for r in records]
    preds = predict_texts(
        best_model,
        tokenizer,
        texts,
        threshold_entity=THRESHOLD_ENTITY,
        threshold_aspect=THRESHOLD_ASPECT,
    )

    rows = []
    for rec, pred in zip(records, preds):
        gold_pairs = parse_full_label(rec.get("full_label", ""))
        pred_pairs = pred.get("pred_aspect_category_sentiments", [])

        gold_label_en = to_english_label(gold_pairs)
        pred_label_en = to_english_label(pred_pairs)

        rows.append({
            "cleaned_review": rec.get("cleaned_review", ""),
            "gold_label_en": gold_label_en,
            "pred_label_en": pred_label_en,
            "gold_raw_full_label": rec.get("full_label", ""),
            "exact_match": int(gold_label_en == pred_label_en),
            "gold_num_pairs": len(gold_pairs),
            "pred_num_pairs": len(pred_pairs),
            "pred_entities": " | ".join(pred.get("pred_entities", [])),
            "pred_aspect_categories": " | ".join(pred.get("pred_aspect_categories", [])),
        })

    df_out = pd.DataFrame(rows)
    out_path = OUTPUT_DIR / f"{split_name}_predictions_english_labels.csv"
    df_out.to_csv(out_path, index=False, encoding="utf-8-sig")

    exact_match_rate = (df_out["exact_match"].mean() * 100.0) if len(df_out) else 0.0
    print(f"[{split_name}] saved: {out_path}")
    print(f"[{split_name}] exact-match: {exact_match_rate:.2f}% ({int(df_out['exact_match'].sum())}/{len(df_out)})")
    return df_out

val_pred_df = save_split_predictions(val_records, "val")
test_pred_df = save_split_predictions(test_records, "test")

display(val_pred_df.head(10))
display(test_pred_df.head(10))

[val] saved: /kaggle/working/hierarchical_outputs/val_predictions_english_labels.csv
[val] exact-match: 15.50% (200/1290)
[test] saved: /kaggle/working/hierarchical_outputs/test_predictions_english_labels.csv
[test] exact-match: 1.40% (7/500)

,cleaned_review,gold_label_en,pred_label_en,gold_raw_full_label,exact_match,gold_num_pairs,pred_num_pairs,pred_entities,pred_aspect_categories
0,,"{FOOD#PRICES, positive}, {FOOD#QUALITY, positive}","{FOOD#PRICES, positive}, {FOOD#QUALITY, positi...","{FOOD#PRICES, positive}, {FOOD#QUALITY, positive}",0,2,3,FOOD,FOOD#PRICES | FOOD#QUALITY | FOOD#STYLE&OPTIONS
1,,"{FOOD#STYLE&OPTIONS, positive}, {RESTAURANT#GE...","{AMBIENCE#GENERAL, neutral}, {FOOD#PRICES, pos...","{FOOD#STYLE&OPTIONS, positive}, {RESTAURANT#GE...",0,3,7,AMBIENCE | FOOD | LOCATION | RESTAURANT,AMBIENCE#GENERAL | FOOD#PRICES | FOOD#QUALITY ...
2,,"{AMBIENCE#GENERAL, positive}, {FOOD#STYLE&OPTI...","{AMBIENCE#GENERAL, positive}, {FOOD#PRICES, po...","{AMBIENCE#GENERAL, positive}, {FOOD#STYLE&OPTI...",0,5,5,AMBIENCE | FOOD | SERVICE,AMBIENCE#GENERAL | FOOD#PRICES | FOOD#QUALITY ...
3,,"{FOOD#QUALITY, positive}, {RESTAURANT#GENERAL,...","{FOOD#QUALITY, positive}, {RESTAURANT#GENERAL,...","{FOOD#QUALITY, positive}, {RESTAURANT#GENERAL,...",1,2,2,FOOD | RESTAURANT,FOOD#QUALITY | RESTAURANT#GENERAL
4,,"{FOOD#QUALITY, positive}","{FOOD#QUALITY, positive}, {FOOD#STYLE&OPTIONS,...","{FOOD#QUALITY, positive}",0,1,2,FOOD,FOOD#QUALITY | FOOD#STYLE&OPTIONS
5,,"{AMBIENCE#GENERAL, neutral}, {FOOD#STYLE&OPTIO...","{AMBIENCE#GENERAL, neutral}, {DRINKS#PRICES, p...","{AMBIENCE#GENERAL, neutral}, {FOOD#STYLE&OPTIO...",0,5,6,AMBIENCE | DRINKS | FOOD | RESTAURANT | SERVICE,AMBIENCE#GENERAL | DRINKS#PRICES | FOOD#PRICES...
6,,"{LOCATION#GENERAL, positive}, {RESTAURANT#MISC...","{AMBIENCE#GENERAL, neutral}, {FOOD#PRICES, neu...","{LOCATION#GENERAL, positive}, {RESTAURANT#MISC...",0,7,7,AMBIENCE | FOOD | LOCATION | RESTAURANT,AMBIENCE#GENERAL | FOOD#PRICES | FOOD#QUALITY ...
7,,"{FOOD#QUALITY, positive}, {FOOD#PRICES, positi...","{AMBIENCE#GENERAL, positive}, {FOOD#PRICES, po...","{FOOD#QUALITY, positive}, {FOOD#PRICES, positi...",0,5,5,AMBIENCE | FOOD | RESTAURANT | SERVICE,AMBIENCE#GENERAL | FOOD#PRICES | FOOD#QUALITY ...
8,,"{FOOD#QUALITY, positive}, {FOOD#PRICES, positive}","{FOOD#PRICES, positive}, {FOOD#QUALITY, positive}","{FOOD#QUALITY, positive}, {FOOD#PRICES, positive}",0,2,2,FOOD,FOOD#PRICES | FOOD#QUALITY
9,,"{LOCATION#GENERAL, neutral}, {RESTAURANT#GENER...","{DRINKS#PRICES, positive}, {DRINKS#STYLE&OPTIO...","{LOCATION#GENERAL, neutral}, {RESTAURANT#GENER...",0,5,7,DRINKS | FOOD | LOCATION | SERVICE,DRINKS#PRICES | DRINKS#STYLE&OPTIONS | FOOD#PR...

,cleaned_review,gold_label_en,pred_label_en,gold_raw_full_label,exact_match,gold_num_pairs,pred_num_pairs,pred_entities,pred_aspect_categories
0,,"{RESTAURANT#GENERAL, positive}, {DRINKS#QUALIT...","{DRINKS#PRICES, neutral}, {DRINKS#QUALITY, neu...","{RESTAURANT#GENERAL, positive}, {DRINKS#QUALIT...",0,4,4,DRINKS,DRINKS#PRICES | DRINKS#QUALITY | DRINKS#STYLE&...
1,,"{LOCATION#GENERAL, neutral}, {RESTAURANT#MISCE...","{DRINKS#STYLE&OPTIONS, positive}, {FOOD#QUALIT...","{LOCATION#GENERAL, neutral}, {RESTAURANT#MISCE...",0,7,6,DRINKS | FOOD | LOCATION | RESTAURANT,DRINKS#STYLE&OPTIONS | FOOD#QUALITY | FOOD#STY...
2,,"{FOOD#STYLE&OPTIONS, positive}, {AMBIENCE#GENE...","{AMBIENCE#GENERAL, positive}, {DRINKS#PRICES, ...","{FOOD#STYLE&OPTIONS, positive}, {AMBIENCE#GENE...",0,6,6,AMBIENCE | DRINKS | FOOD,AMBIENCE#GENERAL | DRINKS#PRICES | DRINKS#QUAL...
3,,"{LOCATION#GENERAL, positive}, {RESTAURANT#PRIC...","{AMBIENCE#GENERAL, positive}, {DRINKS#QUALITY,...","{LOCATION#GENERAL, positive}, {RESTAURANT#PRIC...",0,8,9,AMBIENCE | DRINKS | FOOD | LOCATION | RESTAURA...,AMBIENCE#GENERAL | DRINKS#QUALITY | DRINKS#STY...
4,,"{AMBIENCE#GENERAL, positive}, {RESTAURANT#PRIC...","{AMBIENCE#GENERAL, positive}, {FOOD#PRICES, po...","{AMBIENCE#GENERAL, positive}, {RESTAURANT#PRIC...",0,5,5,AMBIENCE | FOOD | SERVICE,AMBIENCE#GENERAL | FOOD#PRICES | FOOD#QUALITY ...
5,,"{AMBIENCE#GENERAL, positive}, {FOOD#QUALITY, p...","{AMBIENCE#GENERAL, positive}, {FOOD#QUALITY, p...","{AMBIENCE#GENERAL, positive}, {FOOD#QUALITY, p...",1,3,3,AMBIENCE | FOOD | RESTAURANT,AMBIENCE#GENERAL | FOOD#QUALITY | RESTAURANT#G...
6,,"{FOOD#STYLE&OPTIONS, positive}, {FOOD#QUALITY,...","{AMBIENCE#GENERAL, positive}, {FOOD#PRICES, ne...","{FOOD#STYLE&OPTIONS, positive}, {FOOD#QUALITY,...",0,5,7,AMBIENCE | FOOD | RESTAURANT | SERVICE,AMBIENCE#GENERAL | FOOD#PRICES | FOOD#QUALITY ...
7,,"{AMBIENCE#GENERAL, positive}, {FOOD#QUALITY, p...","{AMBIENCE#GENERAL, positive}, {FOOD#PRICES, po...","{AMBIENCE#GENERAL, positive}, {FOOD#QUALITY, p...",0,4,5,AMBIENCE | FOOD | SERVICE,AMBIENCE#GENERAL | FOOD#PRICES | FOOD#QUALITY ...
8,,"{RESTAURANT#GENERAL, positive}, {FOOD#QUALITY,...","{AMBIENCE#GENERAL, positive}, {FOOD#PRICES, po...","{RESTAURANT#GENERAL, positive}, {FOOD#QUALITY,...",0,7,7,AMBIENCE | FOOD | LOCATION | RESTAURANT | SERVICE,AMBIENCE#GENERAL | FOOD#PRICES | FOOD#QUALITY ...
9,,"{LOCATION#GENERAL, negative}, {RESTAURANT#MISC...","{AMBIENCE#GENERAL, positive}, {DRINKS#PRICES, ...","{LOCATION#GENERAL, negative}, {RESTAURANT#MISC...",0,7,10,AMBIENCE | DRINKS | FOOD | LOCATION | RESTAURANT,AMBIENCE#GENERAL | DRINKS#PRICES | DRINKS#QUAL...

In [23]:
def debug_aspect_metrics_per_class(
    model, 
    loader, 
    split_name: str, 
    threshold: float = 0.5
) -> Dict[str, Dict[str, float]]:
    model.eval()
    all_true, all_probs = [], []
    
    with torch.no_grad():
        for batch in tqdm(loader, desc=f"aspect-debug-{split_name}", leave=False):
            # Tuỳ chỉnh lại device sao cho khớp với code hiện tại của em
            input_ids = batch["input_ids"].cuda()
            attention_mask = batch["attention_mask"].cuda()
            y_aspect = batch["y_aspect"].cpu().long()
            
            out = model(input_ids=input_ids, attention_mask=attention_mask)
            probs = out["aspect_probs"].cpu()
            
            all_true.append(y_aspect)
            all_probs.append(probs)

    y_true = torch.cat(all_true, dim=0)
    probs = torch.cat(all_probs, dim=0)
    y_pred = (probs >= threshold).long()

    print(f"\n===== Per-Aspect Metrics on {split_name} (Threshold: {threshold}) =====")
    print(f"{'Aspect Category':<30} | {'Precision':<9} | {'Recall':<9} | {'F1-Score':<9}")
    print("-" * 65)
    
    metrics_per_class = {}
    
    for i in range(probs.shape[1]):
        # Giả định id2aspect_category đã được định nghĩa ở global scope
        class_name = id2aspect_category[i] 
        
        y_t = y_true[:, i]
        y_p = y_pred[:, i]
        
        # Tính toán TP, FP, FN
        tp = (y_t * y_p).sum().float()
        fp = ((1 - y_t) * y_p).sum().float()
        fn = (y_t * (1 - y_p)).sum().float()
        
        # Tính metrics và xử lý lỗi chia cho 0
        precision = tp / (tp + fp) if (tp + fp) > 0 else torch.tensor(0.0)
        recall = tp / (tp + fn) if (tp + fn) > 0 else torch.tensor(0.0)
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else torch.tensor(0.0)
        
        p_val, r_val, f1_val = precision.item(), recall.item(), f1.item()
        
        metrics_per_class[class_name] = {
            "precision": p_val,
            "recall": r_val,
            "f1": f1_val
        }
        
        print(f"{class_name:<30} | {p_val:<9.4f} | {r_val:<9.4f} | {f1_val:<9.4f}")

    return metrics_per_class

with open(OUTPUT_DIR / "test_detailed_metrics.json", "w", encoding="utf-8") as f:
    json.dump(test_detailed, f, ensure_ascii=False, indent=2)

metrics_per_class = debug_aspect_metrics_per_class(best_model, test_loader, "test", 0.5)
metrics_per_class

test-detailed:   0%|          | 0/16 [00:00<?, ?it/s]

aspect-debug-test:   0%|          | 0/16 [00:00<?, ?it/s]

===== Per-Aspect Metrics on test (Threshold: 0.5) =====
Aspect Category                | Precision | Recall    | F1-Score
-----------------------------------------------------------------
AMBIENCE#GENERAL               | 0.8910    | 0.9294    | 0.9098
DRINKS#PRICES                  | 0.7692    | 0.6579    | 0.7092
DRINKS#QUALITY                 | 0.7632    | 0.8169    | 0.7891
DRINKS#STYLE&OPTIONS           | 0.4194    | 0.8478    | 0.5612
FOOD#PRICES                    | 0.8470    | 0.9698    | 0.9042
FOOD#QUALITY                   | 0.9517    | 0.9912    | 0.9711
FOOD#STYLE&OPTIONS             | 0.9112    | 0.9677    | 0.9386
LOCATION#GENERAL               | 0.8833    | 0.8883    | 0.8858
RESTAURANT#GENERAL             | 0.6136    | 0.8475    | 0.7119
RESTAURANT#MISCELLANEOUS       | 0.9375    | 0.3462    | 0.5056
RESTAURANT#PRICES              | 0.4286    | 0.3699    | 0.3971
SERVICE#GENERAL                | 0.8678    | 0.8629    | 0.8653

{'AMBIENCE#GENERAL': {'precision': 0.8909774422645569,
  'recall': 0.929411768913269,
  'f1': 0.9097888469696045},
 'DRINKS#PRICES': {'precision': 0.7692307829856873,
  'recall': 0.6578947305679321,
  'f1': 0.7092198729515076},
 'DRINKS#QUALITY': {'precision': 0.7631579041481018,
  'recall': 0.8169013857841492,
  'f1': 0.7891156673431396},
 'DRINKS#STYLE&OPTIONS': {'precision': 0.4193548262119293,
  'recall': 0.8478260636329651,
  'f1': 0.5611510276794434},
 'FOOD#PRICES': {'precision': 0.8469656705856323,
  'recall': 0.9697884917259216,
  'f1': 0.9042253494262695},
 'FOOD#QUALITY': {'precision': 0.9516806602478027,
  'recall': 0.9912472367286682,
  'f1': 0.971061110496521},
 'FOOD#STYLE&OPTIONS': {'precision': 0.9112149477005005,
  'recall': 0.9677419066429138,
  'f1': 0.9386281967163086},
 'LOCATION#GENERAL': {'precision': 0.8833333253860474,
  'recall': 0.8882681727409363,
  'f1': 0.8857938647270203},
 'RESTAURANT#GENERAL': {'precision': 0.6136363744735718,
  'recall': 0.847533643245697,
  'f1': 0.7118644118309021},
 'RESTAURANT#MISCELLANEOUS': {'precision': 0.9375,
  'recall': 0.3461538553237915,
  'f1': 0.5056179761886597},
 'RESTAURANT#PRICES': {'precision': 0.4285714328289032,
  'recall': 0.36986300349235535,
  'f1': 0.3970588147640228},
 'SERVICE#GENERAL': {'precision': 0.8678160905838013,
  'recall': 0.8628571629524231,
  'f1': 0.8653295040130615}}